import type {
  StudentAttendanceRecord,
  StaffAttendanceRecord,
  AttendanceSession,
  AttendanceException,
  AttendanceLeaveRequest,
  AttendanceAlert,
  AttendanceTrendPoint,
  AttendanceActivityEvent,
  AttendanceRegisterRow,
  AttendanceDaySummary,
  AttendanceStatus,
} from '@/domains/attendance/types';

export const CURRENT_DATE = '2026-07-07';

const studentPool = [
  { id: 'stu-001', name: 'Aarav Sharma', admissionNumber: 'GIS2024001', rollNumber: '01', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', guardianName: 'Rajesh Sharma', guardianPhone: '+91 98765 43210' },
  { id: 'stu-002', name: 'Ananya Iyer', admissionNumber: 'GIS2024002', rollNumber: '02', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', guardianName: 'Lakshmi Iyer', guardianPhone: '+91 98765 43211' },
  { id: 'stu-003', name: 'Karthik Menon', admissionNumber: 'GIS2024003', rollNumber: '03', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', guardianName: 'Suresh Menon', guardianPhone: '+91 98765 43212' },
  { id: 'stu-004', name: 'Priya Nair', admissionNumber: 'GIS2024004', rollNumber: '04', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', guardianName: 'Vijay Nair', guardianPhone: '+91 98765 43213' },
  { id: 'stu-005', name: 'Rohan Gupta', admissionNumber: 'GIS2024005', rollNumber: '05', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', guardianName: 'Amit Gupta', guardianPhone: '+91 98765 43214' },
  { id: 'stu-006', name: 'Sneha Patil', admissionNumber: 'GIS2024006', rollNumber: '06', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', guardianName: 'Vikram Patil', guardianPhone: '+91 98765 43215' },
  { id: 'stu-007', name: 'Aditya Verma', admissionNumber: 'GIS2024007', rollNumber: '07', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', guardianName: 'Rahul Verma', guardianPhone: '+91 98765 43216' },
  { id: 'stu-008', name: 'Ishita Joshi', admissionNumber: 'GIS2024008', rollNumber: '08', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', guardianName: 'Sanjay Joshi', guardianPhone: '+91 98765 43217' },
  { id: 'stu-009', name: 'Vikram Reddy', admissionNumber: 'GIS2024009', rollNumber: '09', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', guardianName: 'Krishna Reddy', guardianPhone: '+91 98765 43218' },
  { id: 'stu-010', name: 'Meera Krishnan', admissionNumber: 'GIS2024010', rollNumber: '10', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', guardianName: 'Gopal Krishnan', guardianPhone: '+91 98765 43219' },
  { id: 'stu-011', name: 'Arjun Mehta', admissionNumber: 'GIS2024011', rollNumber: '01', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', guardianName: 'Prakash Mehta', guardianPhone: '+91 98765 43220' },
  { id: 'stu-012', name: 'Divya Rao', admissionNumber: 'GIS2024012', rollNumber: '02', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', guardianName: 'Narayan Rao', guardianPhone: '+91 98765 43221' },
  { id: 'stu-013', name: 'Rahul Singh', admissionNumber: 'GIS2024013', rollNumber: '03', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', guardianName: 'Satyendra Singh', guardianPhone: '+91 98765 43222' },
  { id: 'stu-014', name: 'Kavita Sharma', admissionNumber: 'GIS2024014', rollNumber: '04', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', guardianName: 'Ashok Sharma', guardianPhone: '+91 98765 43223' },
  { id: 'stu-015', name: 'Siddharth Jha', admissionNumber: 'GIS2024015', rollNumber: '05', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', guardianName: 'Ranjan Jha', guardianPhone: '+91 98765 43224' },
  { id: 'stu-016', name: 'Pooja Desai', admissionNumber: 'GIS2024016', rollNumber: '01', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', guardianName: 'Mahesh Desai', guardianPhone: '+91 98765 43225' },
  { id: 'stu-017', name: 'Nikhil Kulkarni', admissionNumber: 'GIS2024017', rollNumber: '02', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', guardianName: 'Ramesh Kulkarni', guardianPhone: '+91 98765 43226' },
  { id: 'stu-018', name: 'Ritu Agarwal', admissionNumber: 'GIS2024018', rollNumber: '03', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', guardianName: 'Sunil Agarwal', guardianPhone: '+91 98765 43227' },
  { id: 'stu-019', name: 'Amit Trivedi', admissionNumber: 'GIS2024019', rollNumber: '04', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', guardianName: 'Kiran Trivedi', guardianPhone: '+91 98765 43228' },
  { id: 'stu-020', name: 'Shreya Bhat', admissionNumber: 'GIS2024020', rollNumber: '05', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', guardianName: 'Madhav Bhat', guardianPhone: '+91 98765 43229' },
  { id: 'stu-021', name: 'Pranav Pillai', admissionNumber: 'GIS2024021', rollNumber: '01', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-a', sectionName: 'A', guardianName: 'Vinod Pillai', guardianPhone: '+91 98765 43230' },
  { id: 'stu-022', name: 'Tanvi Kaur', admissionNumber: 'GIS2024022', rollNumber: '02', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-a', sectionName: 'A', guardianName: 'Harpreet Kaur', guardianPhone: '+91 98765 43231' },
  { id: 'stu-023', name: 'Yash Chopra', admissionNumber: 'GIS2024023', rollNumber: '03', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-a', sectionName: 'A', guardianName: 'Rohan Chopra', guardianPhone: '+91 98765 43232' },
  { id: 'stu-024', name: 'Ira Deshmukh', admissionNumber: 'GIS2024024', rollNumber: '04', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-a', sectionName: 'A', guardianName: 'Deepak Deshmukh', guardianPhone: '+91 98765 43233' },
  { id: 'stu-025', name: 'Kunal Shah', admissionNumber: 'GIS2024025', rollNumber: '05', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-a', sectionName: 'A', guardianName: 'Nikhil Shah', guardianPhone: '+91 98765 43234' },
  { id: 'stu-026', name: 'Esha Malhotra', admissionNumber: 'GIS2024026', rollNumber: '01', classGradeId: 'cls-7', classGradeName: 'Grade 7', sectionId: 'sec-7-a', sectionName: 'A', guardianName: 'Sanjay Malhotra', guardianPhone: '+91 98765 43235' },
  { id: 'stu-027', name: 'Rohan Saxena', admissionNumber: 'GIS2024027', rollNumber: '02', classGradeId: 'cls-7', classGradeName: 'Grade 7', sectionId: 'sec-7-a', sectionName: 'A', guardianName: 'Alok Saxena', guardianPhone: '+91 98765 43236' },
  { id: 'stu-028', name: 'Diya Venkatesh', admissionNumber: 'GIS2024028', rollNumber: '03', classGradeId: 'cls-7', classGradeName: 'Grade 7', sectionId: 'sec-7-a', sectionName: 'A', guardianName: 'Balaji Venkatesh', guardianPhone: '+91 98765 43237' },
  { id: 'stu-029', name: 'Anirudh Bhatt', admissionNumber: 'GIS2024029', rollNumber: '04', classGradeId: 'cls-7', classGradeName: 'Grade 7', sectionId: 'sec-7-a', sectionName: 'A', guardianName: 'Chetan Bhatt', guardianPhone: '+91 98765 43238' },
  { id: 'stu-030', name: 'Sanya Kapoor', admissionNumber: 'GIS2024030', rollNumber: '05', classGradeId: 'cls-7', classGradeName: 'Grade 7', sectionId: 'sec-7-a', sectionName: 'A', guardianName: 'Manoj Kapoor', guardianPhone: '+91 98765 43239' },
  { id: 'stu-031', name: 'Neel Thakur', admissionNumber: 'GIS2024031', rollNumber: '01', classGradeId: 'cls-6', classGradeName: 'Grade 6', sectionId: 'sec-6-a', sectionName: 'A', guardianName: 'Raj Thakur', guardianPhone: '+91 98765 43240' },
  { id: 'stu-032', name: 'Avni Sharma', admissionNumber: 'GIS2024032', rollNumber: '02', classGradeId: 'cls-6', classGradeName: 'Grade 6', sectionId: 'sec-6-a', sectionName: 'A', guardianName: 'Pankaj Sharma', guardianPhone: '+91 98765 43241' },
  { id: 'stu-033', name: 'Kabir Das', admissionNumber: 'GIS2024033', rollNumber: '03', classGradeId: 'cls-6', classGradeName: 'Grade 6', sectionId: 'sec-6-a', sectionName: 'A', guardianName: 'Shyam Das', guardianPhone: '+91 98765 43242' },
  { id: 'stu-034', name: 'Riya Fernandes', admissionNumber: 'GIS2024034', rollNumber: '04', classGradeId: 'cls-6', classGradeName: 'Grade 6', sectionId: 'sec-6-a', sectionName: 'A', guardianName: 'Carlos Fernandes', guardianPhone: '+91 98765 43243' },
  { id: 'stu-035', name: 'Aryan Mittal', admissionNumber: 'GIS2024035', rollNumber: '05', classGradeId: 'cls-6', classGradeName: 'Grade 6', sectionId: 'sec-6-a', sectionName: 'A', guardianName: 'Vikas Mittal', guardianPhone: '+91 98765 43244' },
  { id: 'stu-036', name: 'Myra Gupta', admissionNumber: 'GIS2024036', rollNumber: '01', classGradeId: 'cls-5', classGradeName: 'Grade 5', sectionId: 'sec-5-a', sectionName: 'A', guardianName: 'Saurabh Gupta', guardianPhone: '+91 98765 43245' },
  { id: 'stu-037', name: 'Vihaan Roy', admissionNumber: 'GIS2024037', rollNumber: '02', classGradeId: 'cls-5', classGradeName: 'Grade 5', sectionId: 'sec-5-a', sectionName: 'A', guardianName: 'Debjit Roy', guardianPhone: '+91 98765 43246' },
  { id: 'stu-038', name: 'Anvi Bose', admissionNumber: 'GIS2024038', rollNumber: '03', classGradeId: 'cls-5', classGradeName: 'Grade 5', sectionId: 'sec-5-a', sectionName: 'A', guardianName: 'Subir Bose', guardianPhone: '+91 98765 43247' },
  { id: 'stu-039', name: 'Krish Bhatia', admissionNumber: 'GIS2024039', rollNumber: '04', classGradeId: 'cls-5', classGradeName: 'Grade 5', sectionId: 'sec-5-a', sectionName: 'A', guardianName: 'Nitin Bhatia', guardianPhone: '+91 98765 43248' },
  { id: 'stu-040', name: 'Prisha Mallick', admissionNumber: 'GIS2024040', rollNumber: '05', classGradeId: 'cls-5', classGradeName: 'Grade 5', sectionId: 'sec-5-a', sectionName: 'A', guardianName: 'Debasis Mallick', guardianPhone: '+91 98765 43249' },
];

const staffPool = [
  { id: 'stf-001', name: 'Rebecca Thomas', employeeCode: 'TCH001', departmentId: 'dept-001', departmentName: 'Mathematics', role: 'Senior Teacher', shift: 'Morning' },
  { id: 'stf-002', name: 'Arjun Mehta', employeeCode: 'TCH002', departmentId: 'dept-002', departmentName: 'Science', role: 'HOD', shift: 'Morning' },
  { id: 'stf-003', name: 'Lakshmi Iyer', employeeCode: 'TCH003', departmentId: 'dept-003', departmentName: 'Languages', role: 'Teacher', shift: 'Morning' },
  { id: 'stf-004', name: 'Ananya Reddy', employeeCode: 'TCH004', departmentId: 'dept-004', departmentName: 'Social Studies', role: 'Teacher', shift: 'Morning' },
  { id: 'stf-005', name: 'Priya Sharma', employeeCode: 'TCH005', departmentId: 'dept-005', departmentName: 'Physical Education', role: 'Sports Coordinator', shift: 'Morning' },
  { id: 'stf-006', name: 'Suresh Pillai', employeeCode: 'ACC001', departmentId: 'dept-007', departmentName: 'Finance & Accounts', role: 'Chief Accountant', shift: 'Full Day' },
  { id: 'stf-007', name: 'Karthik Subramanian', employeeCode: 'OPS001', departmentId: 'dept-008', departmentName: 'Operations & Facilities', role: 'Operations Manager', shift: 'Full Day' },
  { id: 'stf-008', name: 'Rajesh Nair', employeeCode: 'IT001', departmentId: 'dept-009', departmentName: 'IT & Technology', role: 'IT Manager', shift: 'Full Day' },
  { id: 'stf-009', name: 'Geeta Menon', employeeCode: 'LIB001', departmentId: 'dept-010', departmentName: 'Library & Resources', role: 'Librarian', shift: 'Morning' },
  { id: 'stf-010', name: 'Anita Kapoor', employeeCode: 'ADM001', departmentId: 'dept-006', departmentName: 'Administration', role: 'School Administrator', shift: 'Full Day' },
  { id: 'stf-011', name: 'Vikram Rao', employeeCode: 'TCH006', departmentId: 'dept-001', departmentName: 'Mathematics', role: 'Teacher', shift: 'Morning' },
  { id: 'stf-012', name: 'Deepa Venkatesh', employeeCode: 'TCH007', departmentId: 'dept-003', departmentName: 'Languages', role: 'Teacher', shift: 'Morning' },
  { id: 'stf-013', name: 'Mohammed Faisal', employeeCode: 'TCH008', departmentId: 'dept-005', departmentName: 'Physical Education', role: 'PE Teacher', shift: 'Morning' },
  { id: 'stf-014', name: 'Sanjay Gupta', employeeCode: 'TRN001', departmentId: 'dept-008', departmentName: 'Operations & Facilities', role: 'Transport In-Charge', shift: 'Morning' },
  { id: 'stf-015', name: 'Meera Krishnan', employeeCode: 'PRN001', departmentId: 'dept-006', departmentName: 'Administration', role: 'Principal', shift: 'Full Day' },
];

const statusOptions: AttendanceStatus[] = ['Present', 'Absent', 'Late', 'Half Day', 'Leave', 'Excused'];

function randomStatus(): AttendanceStatus {
  const weights = [0.75, 0.05, 0.08, 0.04, 0.05, 0.03];
  const rand = Math.random();
  let sum = 0;
  for (let i = 0; i < weights.length; i++) {
    sum += weights[i];
    if (rand < sum) return statusOptions[i];
  }
  return 'Present';
}

export const studentAttendanceRecords: StudentAttendanceRecord[] = studentPool.map((s, idx) => {
  const status = randomStatus();
  return {
    id: `sar-${idx + 1}`,
    date: CURRENT_DATE,
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    campusId: idx < 30 ? 'camp-001' : 'camp-002',
    campusName: idx < 30 ? 'Greenfield Main Campus' : 'Greenfield Whitefield Campus',
    personType: 'Student',
    personId: s.id,
    personName: s.name,
    status,
    sessionId: `sess-${idx < 30 ? '001' : '002'}`,
    sessionName: 'Daily Attendance',
    markedById: 'stf-001',
    markedByName: 'Rebecca Thomas',
    markedAt: `${CURRENT_DATE}T08:30:00Z`,
    source: 'Manual',
    remarks: status === 'Late' ? 'Arrived 15 minutes late' : null,
    createdAt: `${CURRENT_DATE}T08:30:00Z`,
    updatedAt: `${CURRENT_DATE}T08:30:00Z`,
    studentId: s.id,
    admissionNumber: s.admissionNumber,
    rollNumber: s.rollNumber,
    classGradeId: s.classGradeId,
    classGradeName: s.classGradeName,
    sectionId: s.sectionId,
    sectionName: s.sectionName,
    guardianName: s.guardianName,
    guardianPhone: s.guardianPhone,
    checkInTime: status === 'Present' || status === 'Late' ? '08:15' : null,
    checkOutTime: null,
  };
});

export const staffAttendanceRecords: StaffAttendanceRecord[] = staffPool.map((s, idx) => {
  const status = idx === 3 ? 'Absent' : idx === 7 ? 'Late' : 'Present';
  return {
    id: `sfr-${idx + 1}`,
    date: CURRENT_DATE,
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    personType: 'Staff',
    personId: s.id,
    personName: s.name,
    status,
    sessionId: `sess-s-${idx + 1}`,
    sessionName: 'Staff Attendance',
    markedById: 'stf-010',
    markedByName: 'Anita Kapoor',
    markedAt: `${CURRENT_DATE}T09:00:00Z`,
    source: 'Manual',
    remarks: status === 'Absent' ? 'On sick leave' : status === 'Late' ? 'Traffic delay' : null,
    createdAt: `${CURRENT_DATE}T09:00:00Z`,
    updatedAt: `${CURRENT_DATE}T09:00:00Z`,
    staffId: s.id,
    employeeCode: s.employeeCode,
    departmentId: s.departmentId,
    departmentName: s.departmentName,
    roleName: s.role,
    shiftName: s.shift,
    checkInTime: status === 'Present' || status === 'Late' ? (s.shift === 'Full Day' ? '08:45' : '08:00') : null,
    checkOutTime: null,
    expectedCheckInTime: '08:30',
    expectedCheckOutTime: '16:30',
  };
});

export const attendanceSessions: AttendanceSession[] = [
  {
    id: 'sess-001',
    date: CURRENT_DATE,
    sessionName: 'Grade 10-A Daily Attendance',
    personType: 'Student',
    mode: 'Daily',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    classGradeId: 'cls-10',
    classGradeName: 'Grade 10',
    sectionId: 'sec-10-a',
    sectionName: 'A',
    departmentId: null,
    departmentName: null,
    status: 'Submitted',
    markedById: 'stf-001',
    markedByName: 'Rebecca Thomas',
    submittedAt: `${CURRENT_DATE}T08:35:00Z`,
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    totalCount: 10,
    presentCount: 8,
    absentCount: 1,
    lateCount: 1,
    leaveCount: 0,
    notMarkedCount: 0,
    remarks: null,
  },
  {
    id: 'sess-002',
    date: CURRENT_DATE,
    sessionName: 'Grade 10-B Daily Attendance',
    personType: 'Student',
    mode: 'Daily',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    classGradeId: 'cls-10',
    classGradeName: 'Grade 10',
    sectionId: 'sec-10-b',
    sectionName: 'B',
    departmentId: null,
    departmentName: null,
    status: 'In Progress',
    markedById: 'stf-002',
    markedByName: 'Arjun Mehta',
    submittedAt: null,
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    totalCount: 5,
    presentCount: 4,
    absentCount: 0,
    lateCount: 1,
    leaveCount: 0,
    notMarkedCount: 0,
    remarks: null,
  },
  {
    id: 'sess-003',
    date: CURRENT_DATE,
    sessionName: 'Grade 9-A Daily Attendance',
    personType: 'Student',
    mode: 'Daily',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    classGradeId: 'cls-9',
    classGradeName: 'Grade 9',
    sectionId: 'sec-9-a',
    sectionName: 'A',
    departmentId: null,
    departmentName: null,
    status: 'Draft',
    markedById: 'stf-003',
    markedByName: 'Lakshmi Iyer',
    submittedAt: null,
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    totalCount: 5,
    presentCount: 0,
    absentCount: 0,
    lateCount: 0,
    leaveCount: 0,
    notMarkedCount: 5,
    remarks: null,
  },
  {
    id: 'sess-004',
    date: CURRENT_DATE,
    sessionName: 'Grade 8-A Daily Attendance',
    personType: 'Student',
    mode: 'Daily',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    classGradeId: 'cls-8',
    classGradeName: 'Grade 8',
    sectionId: 'sec-8-a',
    sectionName: 'A',
    departmentId: null,
    departmentName: null,
    status: 'Approved',
    markedById: 'stf-004',
    markedByName: 'Ananya Reddy',
    submittedAt: `${CURRENT_DATE}T08:40:00Z`,
    approvedById: 'stf-015',
    approvedByName: 'Meera Krishnan',
    approvedAt: `${CURRENT_DATE}T09:00:00Z`,
    totalCount: 5,
    presentCount: 5,
    absentCount: 0,
    lateCount: 0,
    leaveCount: 0,
    notMarkedCount: 0,
    remarks: 'All students present',
  },
  {
    id: 'sess-005',
    date: CURRENT_DATE,
    sessionName: 'Grade 7-A Daily Attendance',
    personType: 'Student',
    mode: 'Daily',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    classGradeId: 'cls-7',
    classGradeName: 'Grade 7',
    sectionId: 'sec-7-a',
    sectionName: 'A',
    departmentId: null,
    departmentName: null,
    status: 'Submitted',
    markedById: 'stf-005',
    markedByName: 'Priya Sharma',
    submittedAt: `${CURRENT_DATE}T08:38:00Z`,
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    totalCount: 5,
    presentCount: 4,
    absentCount: 1,
    lateCount: 0,
    leaveCount: 0,
    notMarkedCount: 0,
    remarks: null,
  },
  {
    id: 'sess-006',
    date: CURRENT_DATE,
    sessionName: 'Mathematics Department Staff',
    personType: 'Staff',
    mode: 'Staff Shift',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    classGradeId: null,
    classGradeName: null,
    sectionId: null,
    sectionName: null,
    departmentId: 'dept-001',
    departmentName: 'Mathematics',
    status: 'Approved',
    markedById: 'stf-006',
    markedByName: 'Suresh Pillai',
    submittedAt: `${CURRENT_DATE}T09:00:00Z`,
    approvedById: 'stf-015',
    approvedByName: 'Meera Krishnan',
    approvedAt: `${CURRENT_DATE}T09:15:00Z`,
    totalCount: 2,
    presentCount: 2,
    absentCount: 0,
    lateCount: 0,
    leaveCount: 0,
    notMarkedCount: 0,
    remarks: null,
  },
  {
    id: 'sess-007',
    date: CURRENT_DATE,
    sessionName: 'Science Department Staff',
    personType: 'Staff',
    mode: 'Staff Shift',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    classGradeId: null,
    classGradeName: null,
    sectionId: null,
    sectionName: null,
    departmentId: 'dept-002',
    departmentName: 'Science',
    status: 'Locked',
    markedById: 'stf-006',
    markedByName: 'Suresh Pillai',
    submittedAt: `${CURRENT_DATE}T09:00:00Z`,
    approvedById: 'stf-015',
    approvedByName: 'Meera Krishnan',
    approvedAt: `${CURRENT_DATE}T09:15:00Z`,
    totalCount: 1,
    presentCount: 1,
    absentCount: 0,
    lateCount: 0,
    leaveCount: 0,
    notMarkedCount: 0,
    remarks: null,
  },
  {
    id: 'sess-008',
    date: CURRENT_DATE,
    sessionName: 'Administration Staff',
    personType: 'Staff',
    mode: 'Staff Shift',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    classGradeId: null,
    classGradeName: null,
    sectionId: null,
    sectionName: null,
    departmentId: 'dept-006',
    departmentName: 'Administration',
    status: 'Submitted',
    markedById: 'stf-010',
    markedByName: 'Anita Kapoor',
    submittedAt: `${CURRENT_DATE}T09:05:00Z`,
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    totalCount: 2,
    presentCount: 2,
    absentCount: 0,
    lateCount: 0,
    leaveCount: 0,
    notMarkedCount: 0,
    remarks: null,
  },
];

export const attendanceExceptions: AttendanceException[] = [
  { id: 'exc-001', personType: 'Student', personId: 'stu-003', personName: 'Karthik Menon', date: CURRENT_DATE, type: 'Late Arrival', status: 'Resolved', reason: 'Bus breakdown delayed arrival', reportedBy: 'Class Teacher', reportedAt: `${CURRENT_DATE}T08:45:00Z`, resolvedBy: 'Transport In-Charge', resolvedAt: `${CURRENT_DATE}T09:00:00Z`, notes: 'Verified with transport team' },
  { id: 'exc-002', personType: 'Student', personId: 'stu-018', personName: 'Ritu Agarwal', date: CURRENT_DATE, type: 'Early Departure', status: 'Open', reason: 'Medical appointment', reportedBy: 'Parent', reportedAt: `${CURRENT_DATE}T07:00:00Z`, resolvedBy: null, resolvedAt: null, notes: 'Appointment at 11:30 AM' },
  { id: 'exc-003', personType: 'Staff', personId: 'stf-004', personName: 'Ananya Reddy', date: CURRENT_DATE, type: 'Missing Check-in', status: 'In Progress', reason: 'Biometric system was down', reportedBy: 'System', reportedAt: `${CURRENT_DATE}T08:35:00Z`, resolvedBy: null, resolvedAt: null, notes: 'Manual entry required' },
  { id: 'exc-004', personType: 'Student', personId: 'stu-007', personName: 'Aditya Verma', date: CURRENT_DATE, type: 'Attendance Correction', status: 'Resolved', reason: 'Marked absent by mistake', reportedBy: 'Parent', reportedAt: `${CURRENT_DATE}T10:00:00Z`, resolvedBy: 'Class Teacher', resolvedAt: `${CURRENT_DATE}T10:30:00Z`, notes: 'Student was present, corrected' },
  { id: 'exc-005', personType: 'Staff', personId: 'stf-007', personName: 'Karthik Subramanian', date: CURRENT_DATE, type: 'Late Arrival', status: 'Resolved', reason: 'Traffic congestion on Sarjapur Road', reportedBy: 'Self', reportedAt: `${CURRENT_DATE}T08:50:00Z`, resolvedBy: 'Principal', resolvedAt: `${CURRENT_DATE}T09:00:00Z`, notes: 'Arrived at 9:15 AM' },
  { id: 'exc-006', personType: 'Student', personId: 'stu-025', personName: 'Kunal Shah', date: CURRENT_DATE, type: 'Transport Delay', status: 'Open', reason: 'Bus route change due to road work', reportedBy: 'Transport Desk', reportedAt: `${CURRENT_DATE}T08:00:00Z`, resolvedBy: null, resolvedAt: null, notes: 'Expected late by 30 minutes' },
  { id: 'exc-007', personType: 'Staff', personId: 'stf-012', personName: 'Deepa Venkatesh', date: CURRENT_DATE, type: 'Missing Check-out', status: 'Open', reason: 'Forgot to check out', reportedBy: 'System', reportedAt: `${CURRENT_DATE}T17:00:00Z`, resolvedBy: null, resolvedAt: null, notes: 'Manual correction needed' },
  { id: 'exc-008', personType: 'Student', personId: 'stu-032', personName: 'Avni Sharma', date: CURRENT_DATE, type: 'Medical Exception', status: 'Resolved', reason: 'Doctor visit for routine checkup', reportedBy: 'Parent', reportedAt: `${CURRENT_DATE}T06:00:00Z`, resolvedBy: 'Class Teacher', resolvedAt: `${CURRENT_DATE}T08:00:00Z`, notes: 'Will join after lunch' },
];

export const attendanceLeaveRequests: AttendanceLeaveRequest[] = [
  { id: 'leave-001', personType: 'Staff', personId: 'stf-004', personName: 'Ananya Reddy', fromDate: '2026-07-10', toDate: '2026-07-12', reason: 'Family function', status: 'Pending', requestedBy: 'Ananya Reddy', requestedAt: `${CURRENT_DATE}T09:00:00Z`, approvedBy: null, approvedAt: null, attachmentRequired: false, notes: 'Cousin wedding' },
  { id: 'leave-002', personType: 'Staff', personId: 'stf-008', personName: 'Rajesh Nair', fromDate: '2026-07-14', toDate: '2026-07-14', reason: 'Personal work', status: 'Approved', requestedBy: 'Rajesh Nair', requestedAt: `${CURRENT_DATE}T10:00:00Z`, approvedBy: 'Anita Kapoor', approvedAt: `${CURRENT_DATE}T10:30:00Z`, attachmentRequired: false, notes: null },
  { id: 'leave-003', personType: 'Staff', personId: 'stf-013', personName: 'Mohammed Faisal', fromDate: '2026-07-15', toDate: '2026-07-16', reason: 'Medical leave', status: 'Pending', requestedBy: 'Mohammed Faisal', requestedAt: `${CURRENT_DATE}T11:00:00Z`, approvedBy: null, approvedAt: null, attachmentRequired: true, notes: 'Medical certificate attached' },
  { id: 'leave-004', personType: 'Student', personId: 'stu-015', personName: 'Siddharth Jha', fromDate: '2026-07-08', toDate: '2026-07-09', reason: 'Family trip', status: 'Rejected', requestedBy: 'Parent', requestedAt: '2026-07-05T14:00:00Z', approvedBy: 'Meera Krishnan', approvedAt: '2026-07-06T10:00:00Z', attachmentRequired: false, notes: 'Denied due to upcoming exams' },
  { id: 'leave-005', personType: 'Student', personId: 'stu-022', personName: 'Tanvi Kaur', fromDate: '2026-07-08', toDate: '2026-07-08', reason: 'Medical appointment', status: 'Approved', requestedBy: 'Parent', requestedAt: `${CURRENT_DATE}T07:00:00Z`, approvedBy: 'Class Teacher', approvedAt: `${CURRENT_DATE}T08:00:00Z`, attachmentRequired: false, notes: 'Dental checkup' },
  { id: 'leave-006', personType: 'Staff', personId: 'stf-009', personName: 'Geeta Menon', fromDate: '2026-07-20', toDate: '2026-07-25', reason: 'Annual leave', status: 'Pending', requestedBy: 'Geeta Menon', requestedAt: '2026-07-01T10:00:00Z', approvedBy: null, approvedAt: null, attachmentRequired: false, notes: 'Planned vacation' },
  { id: 'leave-007', personType: 'Student', personId: 'stu-038', personName: 'Anvi Bose', fromDate: '2026-07-09', toDate: '2026-07-10', reason: 'Cultural event participation', status: 'Pending', requestedBy: 'Parent', requestedAt: `${CURRENT_DATE}T12:00:00Z`, approvedBy: null, approvedAt: null, attachmentRequired: false, notes: 'State-level competition' },
  { id: 'leave-008', personType: 'Staff', personId: 'stf-002', personName: 'Arjun Mehta', fromDate: '2026-07-11', toDate: '2026-07-11', reason: 'Personal leave', status: 'Approved', requestedBy: 'Arjun Mehta', requestedAt: '2026-07-05T09:00:00Z', approvedBy: 'Meera Krishnan', approvedAt: '2026-07-06T11:00:00Z', attachmentRequired: false, notes: null },
];

export const attendanceAlerts: AttendanceAlert[] = [
  { id: 'alert-001', title: 'Consecutive Absence Alert', description: 'Rahul Singh has been absent for 3 consecutive days', severity: 'Warning', personType: 'Student', personName: 'Rahul Singh', date: CURRENT_DATE, status: 'Active', actionRequired: 'Contact guardian' },
  { id: 'alert-002', title: 'Late Arrival Pattern', description: 'Ananya Reddy has been late 4 times this week', severity: 'Warning', personType: 'Staff', personName: 'Ananya Reddy', date: CURRENT_DATE, status: 'Active', actionRequired: 'Review and discuss' },
  { id: 'alert-003', title: 'Attendance Threshold', description: 'Grade 7-A attendance below 90% this week', severity: 'Info', personType: 'Student', personName: 'Grade 7-A', date: CURRENT_DATE, status: 'Active', actionRequired: 'Monitor closely' },
  { id: 'alert-004', title: 'Missing Check-out', description: 'Deepa Venkatesh did not check out yesterday', severity: 'Critical', personType: 'Staff', personName: 'Deepa Venkatesh', date: '2026-07-06', status: 'Active', actionRequired: 'Resolve exception' },
  { id: 'alert-005', title: 'Biometric System Issue', description: 'Biometric system was offline for 30 minutes today', severity: 'Warning', personType: 'Staff', personName: 'System', date: CURRENT_DATE, status: 'Acknowledged', actionRequired: 'Verify manual entries' },
  { id: 'alert-006', title: 'High Absentee Count', description: '12 students absent today, above average of 8', severity: 'Info', personType: 'Student', personName: 'School-wide', date: CURRENT_DATE, status: 'Active', actionRequired: 'Review reasons' },
  { id: 'alert-007', title: 'Transport Delay Impact', description: '5 students late due to Bus Route 3 delay', severity: 'Info', personType: 'Student', personName: 'Bus Route 3', date: CURRENT_DATE, status: 'Resolved', actionRequired: 'None' },
  { id: 'alert-008', title: 'Staff Leave Conflict', description: '2 staff from Science Dept. on leave same day', severity: 'Warning', personType: 'Staff', personName: 'Science Department', date: '2026-07-15', status: 'Active', actionRequired: 'Arrange substitute' },
];

export const attendanceTrends: AttendanceTrendPoint[] = [
  { date: '2026-06-24', studentPercentage: 94, staffPercentage: 96, absenteeCount: 105, lateCount: 18 },
  { date: '2026-06-25', studentPercentage: 95, staffPercentage: 97, absenteeCount: 92, lateCount: 15 },
  { date: '2026-06-26', studentPercentage: 93, staffPercentage: 98, absenteeCount: 115, lateCount: 22 },
  { date: '2026-06-27', studentPercentage: 91, staffPercentage: 96, absenteeCount: 142, lateCount: 28 },
  { date: '2026-06-28', studentPercentage: 88, staffPercentage: 92, absenteeCount: 198, lateCount: 35 },
  { date: '2026-06-30', studentPercentage: 95, staffPercentage: 98, absenteeCount: 88, lateCount: 12 },
  { date: '2026-07-01', studentPercentage: 94, staffPercentage: 97, absenteeCount: 98, lateCount: 16 },
  { date: '2026-07-02', studentPercentage: 96, staffPercentage: 98, absenteeCount: 72, lateCount: 10 },
  { date: '2026-07-03', studentPercentage: 93, staffPercentage: 95, absenteeCount: 112, lateCount: 24 },
  { date: '2026-07-04', studentPercentage: 94, staffPercentage: 97, absenteeCount: 95, lateCount: 18 },
  { date: '2026-07-05', studentPercentage: 89, staffPercentage: 94, absenteeCount: 168, lateCount: 32 },
  { date: '2026-07-06', studentPercentage: 92, staffPercentage: 96, absenteeCount: 125, lateCount: 20 },
  { date: '2026-07-07', studentPercentage: 94, staffPercentage: 95, absenteeCount: 98, lateCount: 18 },
];

export const attendanceActivityEvents: AttendanceActivityEvent[] = [
  { id: 'act-001', eventType: 'Student Attendance Submitted', title: 'Grade 10-A attendance submitted', description: 'Daily attendance for Grade 10-A submitted by Rebecca Thomas', actor: 'Rebecca Thomas', timestamp: `${CURRENT_DATE}T08:35:00Z`, severity: 'success', relatedEntity: { type: 'session', id: 'sess-001', name: 'Grade 10-A' } },
  { id: 'act-002', eventType: 'Late Arrival Flagged', title: 'Late arrival flagged', description: 'Karthik Menon arrived 15 minutes late, bus breakdown reported', actor: 'System', timestamp: `${CURRENT_DATE}T08:45:00Z`, severity: 'warning', relatedEntity: { type: 'student', id: 'stu-003', name: 'Karthik Menon' } },
  { id: 'act-003', eventType: 'Staff Attendance Submitted', title: 'Mathematics Dept staff attendance submitted', description: 'All 2 staff members marked present', actor: 'Suresh Pillai', timestamp: `${CURRENT_DATE}T09:00:00Z`, severity: 'success', relatedEntity: { type: 'session', id: 'sess-006', name: 'Mathematics Dept' } },
  { id: 'act-004', eventType: 'Exception Resolved', title: 'Late arrival exception resolved', description: 'Transport delay confirmed and excused for Karthik Menon', actor: 'Transport In-Charge', timestamp: `${CURRENT_DATE}T09:00:00Z`, severity: 'success', relatedEntity: { type: 'exception', id: 'exc-001', name: 'Late Arrival' } },
  { id: 'act-005', eventType: 'Leave Request Approved', title: 'Leave request approved', description: 'Rajesh Nair leave on 2026-07-14 approved by Anita Kapoor', actor: 'Anita Kapoor', timestamp: `${CURRENT_DATE}T10:30:00Z`, severity: 'success', relatedEntity: { type: 'leave', id: 'leave-002', name: 'Rajesh Nair' } },
  { id: 'act-006', eventType: 'Guardian Notification Queued', title: 'Absentee notification queued', description: 'SMS notification queued for guardian of Rahul Singh (3 consecutive absences)', actor: 'System', timestamp: `${CURRENT_DATE}T10:00:00Z`, severity: 'info', relatedEntity: { type: 'student', id: 'stu-013', name: 'Rahul Singh' } },
  { id: 'act-007', eventType: 'Session Approved', title: 'Grade 8-A attendance approved', description: 'Attendance session approved by Meera Krishnan, all students present', actor: 'Meera Krishnan', timestamp: `${CURRENT_DATE}T09:00:00Z`, severity: 'success', relatedEntity: { type: 'session', id: 'sess-004', name: 'Grade 8-A' } },
  { id: 'act-008', eventType: 'Attendance Correction Requested', title: 'Attendance correction requested', description: 'Parent requested correction for Aditya Verma - marked absent but was present', actor: 'Parent', timestamp: `${CURRENT_DATE}T10:00:00Z`, severity: 'warning', relatedEntity: { type: 'student', id: 'stu-007', name: 'Aditya Verma' } },
  { id: 'act-009', eventType: 'Session Locked', title: 'Science Dept staff session locked', description: 'Staff attendance session locked after approval', actor: 'Meera Krishnan', timestamp: `${CURRENT_DATE}T09:20:00Z`, severity: 'info', relatedEntity: { type: 'session', id: 'sess-007', name: 'Science Dept' } },
  { id: 'act-010', eventType: 'Leave Request Rejected', title: 'Leave request rejected', description: 'Siddharth Jha leave request rejected due to upcoming exams', actor: 'Meera Krishnan', timestamp: '2026-07-06T10:00:00Z', severity: 'critical', relatedEntity: { type: 'leave', id: 'leave-004', name: 'Siddharth Jha' } },
  { id: 'act-011', eventType: 'Staff Attendance Submitted', title: 'Administration staff attendance submitted', description: 'Daily attendance for Administration dept submitted', actor: 'Anita Kapoor', timestamp: `${CURRENT_DATE}T09:05:00Z`, severity: 'success', relatedEntity: { type: 'session', id: 'sess-008', name: 'Administration' } },
  { id: 'act-012', eventType: 'Late Arrival Flagged', title: 'Staff late arrival flagged', description: 'Karthik Subramanian arrived late due to traffic', actor: 'System', timestamp: `${CURRENT_DATE}T09:15:00Z`, severity: 'warning', relatedEntity: { type: 'staff', id: 'stf-007', name: 'Karthik Subramanian' } },
];

export const attendanceRegisterRows: AttendanceRegisterRow[] = [
  { id: 'reg-001', personType: 'Student', personId: 'stu-001', personName: 'Aarav Sharma', admissionNumber: 'GIS2024001', rollNumber: '01', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43210', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-002', personType: 'Student', personId: 'stu-002', personName: 'Ananya Iyer', admissionNumber: 'GIS2024002', rollNumber: '02', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43211', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-003', personType: 'Student', personId: 'stu-003', personName: 'Karthik Menon', admissionNumber: 'GIS2024003', rollNumber: '03', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43212', expectedCheckInTime: null, currentStatus: 'Late', remarks: 'Bus breakdown' },
  { id: 'reg-004', personType: 'Student', personId: 'stu-004', personName: 'Priya Nair', admissionNumber: 'GIS2024004', rollNumber: '04', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43213', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-005', personType: 'Student', personId: 'stu-005', personName: 'Rohan Gupta', admissionNumber: 'GIS2024005', rollNumber: '05', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43214', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-006', personType: 'Student', personId: 'stu-006', personName: 'Sneha Patil', admissionNumber: 'GIS2024006', rollNumber: '06', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43215', expectedCheckInTime: null, currentStatus: 'Absent', remarks: 'Unreported absence' },
  { id: 'reg-007', personType: 'Student', personId: 'stu-007', personName: 'Aditya Verma', admissionNumber: 'GIS2024007', rollNumber: '07', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43216', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-008', personType: 'Student', personId: 'stu-008', personName: 'Ishita Joshi', admissionNumber: 'GIS2024008', rollNumber: '08', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43217', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-009', personType: 'Student', personId: 'stu-009', personName: 'Vikram Reddy', admissionNumber: 'GIS2024009', rollNumber: '09', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43218', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-010', personType: 'Student', personId: 'stu-010', personName: 'Meera Krishnan', admissionNumber: 'GIS2024010', rollNumber: '10', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43219', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-011', personType: 'Student', personId: 'stu-011', personName: 'Arjun Mehta', admissionNumber: 'GIS2024011', rollNumber: '01', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43220', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-012', personType: 'Student', personId: 'stu-012', personName: 'Divya Rao', admissionNumber: 'GIS2024012', rollNumber: '02', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43221', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-013', personType: 'Student', personId: 'stu-013', personName: 'Rahul Singh', admissionNumber: 'GIS2024013', rollNumber: '03', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43222', expectedCheckInTime: null, currentStatus: 'Absent', remarks: '3 consecutive absences' },
  { id: 'reg-014', personType: 'Student', personId: 'stu-014', personName: 'Kavita Sharma', admissionNumber: 'GIS2024014', rollNumber: '04', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43223', expectedCheckInTime: null, currentStatus: 'Late', remarks: 'Arrived 20 mins late' },
  { id: 'reg-015', personType: 'Student', personId: 'stu-015', personName: 'Siddharth Jha', admissionNumber: 'GIS2024015', rollNumber: '05', employeeCode: null, classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43224', expectedCheckInTime: null, currentStatus: 'Present', remarks: null },
  { id: 'reg-016', personType: 'Student', personId: 'stu-016', personName: 'Pooja Desai', admissionNumber: 'GIS2024016', rollNumber: '01', employeeCode: null, classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43225', expectedCheckInTime: null, currentStatus: 'Not Marked', remarks: null },
  { id: 'reg-017', personType: 'Student', personId: 'stu-017', personName: 'Nikhil Kulkarni', admissionNumber: 'GIS2024017', rollNumber: '02', employeeCode: null, classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43226', expectedCheckInTime: null, currentStatus: 'Not Marked', remarks: null },
  { id: 'reg-018', personType: 'Student', personId: 'stu-018', personName: 'Ritu Agarwal', admissionNumber: 'GIS2024018', rollNumber: '03', employeeCode: null, classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43227', expectedCheckInTime: null, currentStatus: 'Not Marked', remarks: null },
  { id: 'reg-019', personType: 'Student', personId: 'stu-019', personName: 'Amit Trivedi', admissionNumber: 'GIS2024019', rollNumber: '04', employeeCode: null, classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43228', expectedCheckInTime: null, currentStatus: 'Not Marked', remarks: null },
  { id: 'reg-020', personType: 'Student', personId: 'stu-020', personName: 'Shreya Bhat', admissionNumber: 'GIS2024020', rollNumber: '05', employeeCode: null, classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', departmentName: null, roleName: null, shiftName: null, guardianPhone: '+91 98765 43229', expectedCheckInTime: null, currentStatus: 'Not Marked', remarks: null },
  { id: 'reg-021', personType: 'Staff', personId: 'stf-001', personName: 'Rebecca Thomas', admissionNumber: null, rollNumber: null, employeeCode: 'TCH001', classGradeId: null, classGradeName: null, sectionId: null, sectionName: null, departmentName: 'Mathematics', roleName: 'Senior Teacher', shiftName: 'Morning', guardianPhone: null, expectedCheckInTime: '08:30', currentStatus: 'Present', remarks: null },
  { id: 'reg-022', personType: 'Staff', personId: 'stf-002', personName: 'Arjun Mehta', admissionNumber: null, rollNumber: null, employeeCode: 'TCH002', classGradeId: null, classGradeName: null, sectionId: null, sectionName: null, departmentName: 'Science', roleName: 'HOD', shiftName: 'Morning', guardianPhone: null, expectedCheckInTime: '08:30', currentStatus: 'Present', remarks: null },
  { id: 'reg-023', personType: 'Staff', personId: 'stf-003', personName: 'Lakshmi Iyer', admissionNumber: null, rollNumber: null, employeeCode: 'TCH003', classGradeId: null, classGradeName: null, sectionId: null, sectionName: null, departmentName: 'Languages', roleName: 'Teacher', shiftName: 'Morning', guardianPhone: null, expectedCheckInTime: '08:30', currentStatus: 'Present', remarks: null },
  { id: 'reg-024', personType: 'Staff', personId: 'stf-004', personName: 'Ananya Reddy', admissionNumber: null, rollNumber: null, employeeCode: 'TCH004', classGradeId: null, classGradeName: null, sectionId: null, sectionName: null, departmentName: 'Social Studies', roleName: 'Teacher', shiftName: 'Morning', guardianPhone: null, expectedCheckInTime: '08:30', currentStatus: 'Absent', remarks: 'On sick leave' },
  { id: 'reg-025', personType: 'Staff', personId: 'stf-005', personName: 'Priya Sharma', admissionNumber: null, rollNumber: null, employeeCode: 'TCH005', classGradeId: null, classGradeName: null, sectionId: null, sectionName: null, departmentName: 'Physical Education', roleName: 'Sports Coordinator', shiftName: 'Morning', guardianPhone: null, expectedCheckInTime: '08:30', currentStatus: 'Present', remarks: null },
  { id: 'reg-026', personType: 'Staff', personId: 'stf-006', personName: 'Suresh Pillai', admissionNumber: null, rollNumber: null, employeeCode: 'ACC001', classGradeId: null, classGradeName: null, sectionId: null, sectionName: null, departmentName: 'Finance & Accounts', roleName: 'Chief Accountant', shiftName: 'Full Day', guardianPhone: null, expectedCheckInTime: '08:30', currentStatus: 'Present', remarks: null },
  { id: 'reg-027', personType: 'Staff', personId: 'stf-007', personName: 'Karthik Subramanian', admissionNumber: null, rollNumber: null, employeeCode: 'OPS001', classGradeId: null, classGradeName: null, sectionId: null, sectionName: null, departmentName: 'Operations & Facilities', roleName: 'Operations Manager', shiftName: 'Full Day', guardianPhone: null, expectedCheckInTime: '08:30', currentStatus: 'Late', remarks: 'Traffic congestion' },
  { id: 'reg-028', personType: 'Staff', personId: 'stf-008', personName: 'Rajesh Nair', admissionNumber: null, rollNumber: null, employeeCode: 'IT001', classGradeId: null, classGradeName: null, sectionId: null, sectionName: null, departmentName: 'IT & Technology', roleName: 'IT Manager', shiftName: 'Full Day', guardianPhone: null, expectedCheckInTime: '08:30', currentStatus: 'Present', remarks: null },
  { id: 'reg-029', personType: 'Staff', personId: 'stf-009', personName: 'Geeta Menon', admissionNumber: null, rollNumber: null, employeeCode: 'LIB001', classGradeId: null, classGradeName: null, sectionId: null, sectionName: null, departmentName: 'Library & Resources', roleName: 'Librarian', shiftName: 'Morning', guardianPhone: null, expectedCheckInTime: '08:30', currentStatus: 'Present', remarks: null },
  { id: 'reg-030', personType: 'Staff', personId: 'stf-010', personName: 'Anita Kapoor', admissionNumber: null, rollNumber: null, employeeCode: 'ADM001', classGradeId: null, classGradeName: null, sectionId: null, sectionName: null, departmentName: 'Administration', roleName: 'School Administrator', shiftName: 'Full Day', guardianPhone: null, expectedCheckInTime: '08:30', currentStatus: 'Present', remarks: null },
];

export const dailyAttendanceSummary: AttendanceDaySummary = {
  date: CURRENT_DATE,
  campusId: 'camp-001',
  campusName: 'Greenfield Main Campus',
  studentTotal: studentAttendanceRecords.length,
  studentPresent: studentAttendanceRecords.filter((r) => r.status === 'Present' || r.status === 'Late').length,
  studentAbsent: studentAttendanceRecords.filter((r) => r.status === 'Absent').length,
  studentLate: studentAttendanceRecords.filter((r) => r.status === 'Late').length,
  studentLeave: studentAttendanceRecords.filter((r) => r.status === 'Leave').length,
  studentPercentage: Math.round(
    (studentAttendanceRecords.filter((r) => r.status === 'Present' || r.status === 'Late').length / studentAttendanceRecords.length) * 100
  ),
  staffTotal: staffAttendanceRecords.length,
  staffPresent: staffAttendanceRecords.filter((r) => r.status === 'Present' || r.status === 'Late').length,
  staffAbsent: staffAttendanceRecords.filter((r) => r.status === 'Absent').length,
  staffLate: staffAttendanceRecords.filter((r) => r.status === 'Late').length,
  staffLeave: staffAttendanceRecords.filter((r) => r.status === 'Leave').length,
  staffPercentage: Math.round(
    (staffAttendanceRecords.filter((r) => r.status === 'Present' || r.status === 'Late').length / staffAttendanceRecords.length) * 100
  ),
};
