import type { WorkingDay, Holiday } from '@/domains/school-setup/types';

export const workingDays: WorkingDay[] = [
  { day: 'Monday', isWorking: true, startTime: '08:00', endTime: '15:30' },
  { day: 'Tuesday', isWorking: true, startTime: '08:00', endTime: '15:30' },
  { day: 'Wednesday', isWorking: true, startTime: '08:00', endTime: '15:30' },
  { day: 'Thursday', isWorking: true, startTime: '08:00', endTime: '15:30' },
  { day: 'Friday', isWorking: true, startTime: '08:00', endTime: '15:30' },
  { day: 'Saturday', isWorking: true, startTime: '08:00', endTime: '12:30' },
  { day: 'Sunday', isWorking: false, startTime: '', endTime: '' },
];

export const holidays: Holiday[] = [
  {
    id: 'hol-001',
    name: 'Summer Break',
    date: '2026-04-15',
    endDate: '2026-05-31',
    type: 'seasonal',
    appliesTo: 'all',
    appliesToName: 'All Campuses',
  },
  {
    id: 'hol-002',
    name: 'Independence Day',
    date: '2026-08-15',
    type: 'national',
    appliesTo: 'all',
    appliesToName: 'All Campuses',
  },
  {
    id: 'hol-003',
    name: 'Raksha Bandhan',
    date: '2026-08-09',
    type: 'religious',
    appliesTo: 'all',
    appliesToName: 'All Campuses',
  },
  {
    id: 'hol-004',
    name: 'Janmashtami',
    date: '2026-08-26',
    type: 'religious',
    appliesTo: 'all',
    appliesToName: 'All Campuses',
  },
  {
    id: 'hol-005',
    name: 'Gandhi Jayanti',
    date: '2026-10-02',
    type: 'national',
    appliesTo: 'all',
    appliesToName: 'All Campuses',
  },
  {
    id: 'hol-006',
    name: 'Dussehra Break',
    date: '2026-10-10',
    endDate: '2026-10-18',
    type: 'religious',
    appliesTo: 'all',
    appliesToName: 'All Campuses',
  },
  {
    id: 'hol-007',
    name: 'Diwali Break',
    date: '2026-10-31',
    endDate: '2026-11-04',
    type: 'religious',
    appliesTo: 'all',
    appliesToName: 'All Campuses',
  },
  {
    id: 'hol-008',
    name: 'Christmas Break',
    date: '2026-12-23',
    endDate: '2027-01-02',
    type: 'seasonal',
    appliesTo: 'all',
    appliesToName: 'All Campuses',
  },
  {
    id: 'hol-009',
    name: 'Republic Day',
    date: '2027-01-26',
    type: 'national',
    appliesTo: 'all',
    appliesToName: 'All Campuses',
  },
  {
    id: 'hol-010',
    name: 'Mid-Term Exams',
    date: '2026-09-15',
    endDate: '2026-09-25',
    type: 'exam',
    appliesTo: 'camp-001',
    appliesToName: 'Main Campus',
  },
  {
    id: 'hol-011',
    name: 'Annual Day',
    date: '2026-11-20',
    type: 'school',
    appliesTo: 'camp-001',
    appliesToName: 'Main Campus',
  },
  {
    id: 'hol-012',
    name: 'Sports Day',
    date: '2026-12-12',
    type: 'school',
    appliesTo: 'camp-002',
    appliesToName: 'Whitefield Campus',
  },
];
