import type { Department } from '@/domains/school-setup/types';

export const departments: Department[] = [
  {
    id: 'dept-001',
    name: 'Mathematics',
    code: 'MATH',
    type: 'Academic',
    headOfDepartment: 'Rebecca Thomas',
    staffCount: 12,
    description: 'Algebra, geometry, calculus, and statistics across all grade levels.',
    status: 'active',
  },
  {
    id: 'dept-002',
    name: 'Science',
    code: 'SCI',
    type: 'Academic',
    headOfDepartment: 'Arjun Mehta',
    staffCount: 15,
    description: 'Physics, chemistry, and biology with laboratory integration.',
    status: 'active',
  },
  {
    id: 'dept-003',
    name: 'Languages',
    code: 'LANG',
    type: 'Academic',
    headOfDepartment: 'Lakshmi Iyer',
    staffCount: 14,
    description: 'English, Hindi, Kannada, and Sanskrit instruction.',
    status: 'active',
  },
  {
    id: 'dept-004',
    name: 'Social Studies',
    code: 'SOC',
    type: 'Academic',
    headOfDepartment: 'Deepa Venkatesh',
    staffCount: 8,
    description: 'History, geography, civics, and economics.',
    status: 'active',
  },
  {
    id: 'dept-005',
    name: 'Physical Education',
    code: 'PED',
    type: 'Academic',
    headOfDepartment: 'Mohammed Faisal',
    staffCount: 5,
    description: 'Sports, fitness, and physical wellness programs.',
    status: 'active',
  },
  {
    id: 'dept-006',
    name: 'Administration',
    code: 'ADMIN',
    type: 'Administrative',
    headOfDepartment: 'Anita Kapoor',
    staffCount: 6,
    description: 'Front office, admissions coordination, and school administration.',
    status: 'active',
  },
  {
    id: 'dept-007',
    name: 'Finance & Accounts',
    code: 'FIN',
    type: 'Finance',
    headOfDepartment: 'Suresh Pillai',
    staffCount: 5,
    description: 'Fee collection, payroll, invoicing, and financial reporting.',
    status: 'active',
  },
  {
    id: 'dept-008',
    name: 'Operations & Facilities',
    code: 'OPS',
    type: 'Operations',
    headOfDepartment: 'Karthik Subramanian',
    staffCount: 18,
    description: 'Transport, maintenance, housekeeping, and facility management.',
    status: 'active',
  },
  {
    id: 'dept-009',
    name: 'IT & Technology',
    code: 'IT',
    type: 'Support',
    headOfDepartment: 'Rajesh Nair',
    staffCount: 4,
    description: 'Infrastructure, software systems, and technical support.',
    status: 'active',
  },
  {
    id: 'dept-010',
    name: 'Library & Resources',
    code: 'LIB',
    type: 'Support',
    headOfDepartment: 'Geeta Menon',
    staffCount: 3,
    description: 'Library management, digital resources, and reading programs.',
    status: 'active',
  },
];
