import type {
  Role,
  PermissionGroup,
  Permission,
  RolePermissionMatrix,
  AccessPolicy,
  UserRole,
  PermissionGroupSlug,
  AccessLevel,
} from '@/domains/identity-access/types';

export const roles: Role[] = [
  {
    slug: 'super-admin',
    name: 'Super Admin',
    description:
      'Full system control across all schools, campuses, and domains. Can configure infrastructure and override any policy.',
    userCount: 2,
    accessLevel: 'full',
  },
  {
    slug: 'school-admin',
    name: 'School Admin',
    description:
      'Manages all operations for a single school — users, settings, finance, and configuration across every domain.',
    userCount: 4,
    accessLevel: 'full',
  },
  {
    slug: 'principal',
    name: 'Principal',
    description:
      'Oversees academics, staff, and school-wide operations. Approves major academic and disciplinary decisions.',
    userCount: 3,
    accessLevel: 'manage',
  },
  {
    slug: 'academic-coordinator',
    name: 'Academic Coordinator',
    description:
      'Manages curriculum, timetables, exams, and academic performance across grades and sections.',
    userCount: 6,
    accessLevel: 'manage',
  },
  {
    slug: 'teacher',
    name: 'Teacher',
    description:
      'Manages attendance, homework, marks, and communication for assigned classes and subjects.',
    userCount: 68,
    accessLevel: 'view',
  },
  {
    slug: 'accountant',
    name: 'Accountant',
    description:
      'Handles fee collection, invoicing, expenses, and financial reporting.',
    userCount: 5,
    accessLevel: 'manage',
  },
  {
    slug: 'admissions-officer',
    name: 'Admissions Officer',
    description:
      'Manages inquiries, applications, enrollment, and student onboarding.',
    userCount: 4,
    accessLevel: 'manage',
  },
  {
    slug: 'staff',
    name: 'Staff',
    description:
      'Non-teaching staff with access to operations, documents, and limited communication tools.',
    userCount: 22,
    accessLevel: 'limited',
  },
  {
    slug: 'parent',
    name: 'Parent',
    description:
      'Views child attendance, marks, homework, and fees. Communicates with teachers and school administration.',
    userCount: 1240,
    accessLevel: 'limited',
  },
  {
    slug: 'student',
    name: 'Student',
    description:
      'Views timetable, homework, marks, attendance, and school announcements.',
    userCount: 1847,
    accessLevel: 'limited',
  },
];

export const permissionGroups: PermissionGroup[] = [
  { slug: 'dashboard', label: 'Dashboard', description: 'School-wide overview and quick actions' },
  { slug: 'identity-access', label: 'Identity & Access', description: 'Users, roles, permissions, and security' },
  { slug: 'school-setup', label: 'School Setup', description: 'Campuses, departments, and configuration' },
  { slug: 'student-lifecycle', label: 'Student Lifecycle', description: 'Admissions, enrollment, and alumni' },
  { slug: 'academics', label: 'Academics', description: 'Classes, subjects, timetables, and curriculum' },
  { slug: 'attendance', label: 'Attendance', description: 'Daily attendance and trends' },
  { slug: 'exams-marks', label: 'Exams & Marks', description: 'Exam scheduling, grading, and report cards' },
  { slug: 'homework', label: 'Homework', description: 'Assignments, submissions, and feedback' },
  { slug: 'staff', label: 'Staff', description: 'Teachers, payroll, and performance' },
  { slug: 'finance', label: 'Finance', description: 'Fees, invoices, expenses, and budgets' },
  { slug: 'communication', label: 'Communication', description: 'Announcements and messaging' },
  { slug: 'notifications', label: 'Notifications', description: 'Alerts, reminders, and delivery' },
  { slug: 'workflows', label: 'Workflows', description: 'Approvals and automations' },
  { slug: 'documents', label: 'Documents', description: 'Templates, records, and certificates' },
  { slug: 'operations', label: 'Operations', description: 'Facilities, transport, and inventory' },
  { slug: 'analytics', label: 'Analytics', description: 'Reports and institutional insights' },
  { slug: 'ai-workspace', label: 'AI Workspace', description: 'AI-assisted drafting and insights' },
  { slug: 'settings', label: 'Settings', description: 'System preferences and integrations' },
];

export const permissions: Permission[] = permissionGroups.map((group) => ({
  group: group.slug,
  label: group.label,
  actions: ['view', 'create', 'edit', 'delete', 'approve', 'export', 'manage'],
}));

const allGroups: PermissionGroupSlug[] = permissionGroups.map((g) => g.slug);

function fill(
  level: AccessLevel,
  overrides: Partial<Record<PermissionGroupSlug, AccessLevel>> = {}
): Partial<Record<PermissionGroupSlug, AccessLevel>> {
  const result: Partial<Record<PermissionGroupSlug, AccessLevel>> = {};
  for (const slug of allGroups) {
    result[slug] = overrides[slug] ?? level;
  }
  return result;
}

export const rolePermissionMatrix: RolePermissionMatrix = {
  'super-admin': fill('full'),
  'school-admin': fill('full', { 'ai-workspace': 'manage' }),
  principal: fill('manage', {
    'identity-access': 'view',
    'school-setup': 'view',
    finance: 'view',
    operations: 'view',
    settings: 'view',
    'ai-workspace': 'view',
  }),
  'academic-coordinator': fill('view', {
    'student-lifecycle': 'manage',
    academics: 'manage',
    attendance: 'manage',
    'exams-marks': 'manage',
    homework: 'manage',
    staff: 'view',
    analytics: 'view',
    documents: 'manage',
    communication: 'manage',
    'identity-access': 'none',
    'school-setup': 'none',
    finance: 'none',
    operations: 'none',
    settings: 'none',
    'ai-workspace': 'view',
    notifications: 'view',
    workflows: 'view',
  }),
  teacher: fill('view', {
    'student-lifecycle': 'none',
    academics: 'view',
    attendance: 'manage',
    'exams-marks': 'manage',
    homework: 'manage',
    staff: 'none',
    finance: 'none',
    communication: 'manage',
    notifications: 'view',
    workflows: 'none',
    documents: 'view',
    operations: 'none',
    analytics: 'view',
    'ai-workspace': 'view',
    'identity-access': 'none',
    'school-setup': 'none',
    settings: 'none',
  }),
  accountant: fill('view', {
    finance: 'manage',
    'student-lifecycle': 'view',
    academics: 'none',
    attendance: 'none',
    'exams-marks': 'none',
    homework: 'none',
    staff: 'view',
    communication: 'view',
    notifications: 'view',
    workflows: 'view',
    documents: 'view',
    operations: 'none',
    analytics: 'view',
    'ai-workspace': 'none',
    'identity-access': 'none',
    'school-setup': 'none',
    settings: 'none',
  }),
  'admissions-officer': fill('view', {
    'student-lifecycle': 'manage',
    finance: 'view',
    academics: 'view',
    attendance: 'none',
    'exams-marks': 'none',
    homework: 'none',
    staff: 'none',
    communication: 'manage',
    notifications: 'view',
    workflows: 'view',
    documents: 'manage',
    operations: 'none',
    analytics: 'view',
    'ai-workspace': 'none',
    'identity-access': 'none',
    'school-setup': 'none',
    settings: 'none',
  }),
  staff: fill('view', {
    dashboard: 'view',
    'identity-access': 'none',
    'school-setup': 'none',
    'student-lifecycle': 'none',
    academics: 'none',
    attendance: 'none',
    'exams-marks': 'none',
    homework: 'none',
    staff: 'none',
    finance: 'none',
    communication: 'view',
    notifications: 'view',
    workflows: 'none',
    documents: 'view',
    operations: 'manage',
    analytics: 'none',
    'ai-workspace': 'none',
    settings: 'none',
  }),
  parent: fill('view', {
    dashboard: 'view',
    'identity-access': 'none',
    'school-setup': 'none',
    'student-lifecycle': 'view',
    academics: 'view',
    attendance: 'view',
    'exams-marks': 'view',
    homework: 'view',
    staff: 'none',
    finance: 'view',
    communication: 'view',
    notifications: 'view',
    workflows: 'none',
    documents: 'view',
    operations: 'none',
    analytics: 'none',
    'ai-workspace': 'none',
    settings: 'none',
  }),
  student: fill('view', {
    dashboard: 'view',
    'identity-access': 'none',
    'school-setup': 'none',
    'student-lifecycle': 'none',
    academics: 'view',
    attendance: 'view',
    'exams-marks': 'view',
    homework: 'view',
    staff: 'none',
    finance: 'none',
    communication: 'view',
    notifications: 'view',
    workflows: 'none',
    documents: 'none',
    operations: 'none',
    analytics: 'none',
    'ai-workspace': 'none',
    settings: 'none',
  }),
};

export const accessPolicies: AccessPolicy[] = [
  {
    id: 'policy-001',
    name: 'Admin MFA Policy',
    description: 'All administrative roles must use multi-factor authentication for every login.',
    appliesTo: ['super-admin', 'school-admin', 'principal'] as UserRole[],
    enforceMfa: true,
    sessionTimeoutMinutes: 30,
    ipRestriction: 'School network + approved IPs',
  },
  {
    id: 'policy-002',
    name: 'Staff Session Policy',
    description: 'Teaching and non-teaching staff sessions expire after 8 hours of inactivity.',
    appliesTo: ['teacher', 'academic-coordinator', 'staff'] as UserRole[],
    enforceMfa: false,
    sessionTimeoutMinutes: 480,
  },
  {
    id: 'policy-003',
    name: 'Parent & Student Policy',
    description: 'Parents and students access the portal with standard security. No MFA required.',
    appliesTo: ['parent', 'student'] as UserRole[],
    enforceMfa: false,
    sessionTimeoutMinutes: 1440,
  },
  {
    id: 'policy-004',
    name: 'Finance Access Policy',
    description: 'Accountant and finance roles require MFA and are restricted to approved IP ranges.',
    appliesTo: ['accountant'] as UserRole[],
    enforceMfa: true,
    sessionTimeoutMinutes: 60,
    ipRestriction: 'Finance office IPs only',
  },
];
