import type { Session } from '@/domains/identity-access/types';

export const sessions: Session[] = [
  {
    id: 'ses-001',
    userId: 'usr-001',
    userName: 'Anita Kapoor',
    avatarInitials: 'AK',
    device: 'MacBook Pro 14"',
    browser: 'Chrome 126',
    location: 'Mumbai, IN',
    ipAddress: '103.21.58.42',
    lastActive: '2 minutes ago',
    status: 'active',
  },
  {
    id: 'ses-002',
    userId: 'usr-003',
    userName: 'Dr. Meera Krishnan',
    avatarInitials: 'MK',
    device: 'Dell Latitude 5440',
    browser: 'Edge 126',
    location: 'Mumbai, IN',
    ipAddress: '103.21.58.51',
    lastActive: '15 minutes ago',
    status: 'active',
  },
  {
    id: 'ses-003',
    userId: 'usr-002',
    userName: 'Rajesh Nair',
    avatarInitials: 'RN',
    device: 'Windows Desktop',
    browser: 'Firefox 127',
    location: 'Bengaluru, IN',
    ipAddress: '49.205.12.88',
    lastActive: '1 hour ago',
    status: 'idle',
  },
  {
    id: 'ses-004',
    userId: 'usr-005',
    userName: 'Rebecca Thomas',
    avatarInitials: 'RT',
    device: 'iPad Air',
    browser: 'Safari 17',
    location: 'Mumbai, IN',
    ipAddress: '103.21.58.73',
    lastActive: '3 hours ago',
    status: 'idle',
  },
  {
    id: 'ses-005',
    userId: 'usr-006',
    userName: 'Suresh Pillai',
    avatarInitials: 'SP',
    device: 'Lenovo ThinkPad',
    browser: 'Chrome 126',
    location: 'Mumbai, IN',
    ipAddress: '103.21.58.90',
    lastActive: '5 hours ago',
    status: 'active',
  },
  {
    id: 'ses-006',
    userId: 'usr-007',
    userName: 'Priya Sharma',
    avatarInitials: 'PS',
    device: 'iPhone 15 Pro',
    browser: 'Safari Mobile',
    location: 'Pune, IN',
    ipAddress: '157.33.40.12',
    lastActive: '8 hours ago',
    status: 'expired',
  },
  {
    id: 'ses-007',
    userId: 'usr-004',
    userName: 'Vikram Rao',
    avatarInitials: 'VR',
    device: 'MacBook Air M2',
    browser: 'Chrome 126',
    location: 'Mumbai, IN',
    ipAddress: '103.21.58.65',
    lastActive: '20 hours ago',
    status: 'expired',
  },
];
