import type {
  HomeworkTask,
  HomeworkAttachment,
  HomeworkAudience,
  HomeworkSubmission,
  HomeworkReview,
  HomeworkClassSummary,
  HomeworkSubjectSummary,
  HomeworkStudentProgress,
  HomeworkAlert,
  HomeworkActivityEvent,
  TaskChecklistItem,
  LearningTaskTemplate,
} from '../types';

const CURRENT_DATE = '2026-07-08';

// Homework Tasks (20)
export const homeworkTasks: HomeworkTask[] = [
  {
    id: 'task-001',
    title: 'English Reading Response - Chapter 5',
    description: 'Read Chapter 5 of "The Adventure of the Speckled Band" and write a 300-word response analyzing the detective\'s methods.',
    taskType: 'Reading',
    subjectId: 'sub-eng',
    subjectName: 'English',
    teacherId: 'stf-003',
    teacherName: 'Lakshmi Iyer',
    classGradeId: 'cls-10',
    classGradeName: 'Grade 10',
    sectionId: 'sec-10-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-01',
    dueDate: '2026-07-08',
    status: 'Due Today',
    priority: 'Medium',
    estimatedDurationMinutes: 45,
    totalStudents: 10,
    submissionCount: 7,
    reviewedCount: 4,
    attachmentCount: 1,
    tags: ['Reading', 'Literature', 'Analysis'],
    instructions: 'Write your response in a Word document. Cite at least 2 examples from the text.',
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-07-07T15:00:00Z',
  },
  {
    id: 'task-002',
    title: 'Mathematics Worksheet - Quadratic Equations',
    description: 'Solve all problems from Exercise 4.2 on quadratic equations. Show all working steps.',
    taskType: 'Worksheet',
    subjectId: 'sub-math',
    subjectName: 'Mathematics',
    teacherId: 'stf-001',
    teacherName: 'Rebecca Thomas',
    classGradeId: 'cls-10',
    classGradeName: 'Grade 10',
    sectionId: 'sec-10-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-03',
    dueDate: '2026-07-10',
    status: 'Published',
    priority: 'High',
    estimatedDurationMinutes: 60,
    totalStudents: 10,
    submissionCount: 3,
    reviewedCount: 0,
    attachmentCount: 1,
    tags: ['Algebra', 'Practice', 'Board Exam Prep'],
    instructions: 'Submit your solved worksheet as PDF. Ensure your handwriting is legible.',
    createdAt: '2026-07-03T08:00:00Z',
    updatedAt: '2026-07-03T08:00:00Z',
  },
  {
    id: 'task-003',
    title: 'Science Lab Observation - Photosynthesis',
    description: 'Record your observations from the photosynthesis experiment conducted on Monday. Include diagrams.',
    taskType: 'Activity',
    subjectId: 'sub-sci',
    subjectName: 'Science',
    teacherId: 'stf-002',
    teacherName: 'Arjun Mehta',
    classGradeId: 'cls-10',
    classGradeName: 'Grade 10',
    sectionId: 'sec-10-b',
    sectionName: 'B',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-01',
    dueDate: '2026-07-07',
    status: 'Overdue',
    priority: 'Medium',
    estimatedDurationMinutes: 40,
    totalStudents: 8,
    submissionCount: 5,
    reviewedCount: 3,
    attachmentCount: 2,
    tags: ['Biology', 'Lab Work', 'Practical'],
    instructions: 'Use the lab observation template provided. Include labeled diagrams of the leaf sections.',
    createdAt: '2026-07-01T11:00:00Z',
    updatedAt: '2026-07-08T09:00:00Z',
  },
  {
    id: 'task-004',
    title: 'Social Science Map Practice - Indian States',
    description: 'Mark all Indian states and their capitals on the blank map provided. Use color coding.',
    taskType: 'Worksheet',
    subjectId: 'sub-ss',
    subjectName: 'Social Studies',
    teacherId: 'stf-004',
    teacherName: 'Ananya Reddy',
    classGradeId: 'cls-8',
    classGradeName: 'Grade 8',
    sectionId: 'sec-8-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-05',
    dueDate: '2026-07-12',
    status: 'Published',
    priority: 'Low',
    estimatedDurationMinutes: 30,
    totalStudents: 12,
    submissionCount: 2,
    reviewedCount: 0,
    attachmentCount: 1,
    tags: ['Geography', 'Map Work', 'Memorization'],
    instructions: 'Use different colors for different regions. Create a legend for reference.',
    createdAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-07-05T10:00:00Z',
  },
  {
    id: 'task-005',
    title: 'Hindi Grammar Worksheet - Sandhi',
    description: 'Complete the Sanskrit Sandhi exercises. Identify and apply the correct Sandhi rules.',
    taskType: 'Worksheet',
    subjectId: 'sub-hindi',
    subjectName: 'Hindi',
    teacherId: 'stf-012',
    teacherName: 'Deepa Venkatesh',
    classGradeId: 'cls-9',
    classGradeName: 'Grade 9',
    sectionId: 'sec-9-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-04',
    dueDate: '2026-07-11',
    status: 'Published',
    priority: 'Medium',
    estimatedDurationMinutes: 35,
    totalStudents: 10,
    submissionCount: 6,
    reviewedCount: 2,
    attachmentCount: 1,
    tags: ['Grammar', 'Sanskrit', 'Language'],
    instructions: 'Submit handwritten solutions. Reference the textbook examples before attempting.',
    createdAt: '2026-07-04T08:30:00Z',
    updatedAt: '2026-07-07T14:00:00Z',
  },
  {
    id: 'task-006',
    title: 'Computer Science Coding Exercise - Loops',
    description: 'Write Python programs to solve the 5 given problems using loops. Include comments.',
    taskType: 'Practice',
    subjectId: 'sub-cs',
    subjectName: 'Computer Science',
    teacherId: 'stf-008',
    teacherName: 'Rajesh Nair',
    classGradeId: 'cls-10',
    classGradeName: 'Grade 10',
    sectionId: 'sec-10-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-06',
    dueDate: '2026-07-13',
    status: 'Published',
    priority: 'High',
    estimatedDurationMinutes: 90,
    totalStudents: 10,
    submissionCount: 1,
    reviewedCount: 0,
    attachmentCount: 1,
    tags: ['Programming', 'Python', 'Logic'],
    instructions: 'Submit .py files. Test your code before submission. Include expected output as comments.',
    createdAt: '2026-07-06T09:00:00Z',
    updatedAt: '2026-07-06T09:00:00Z',
  },
  {
    id: 'task-007',
    title: 'Physics Numericals - Laws of Motion',
    description: 'Solve 15 numerical problems from Chapter 3 on Newton\'s Laws of Motion.',
    taskType: 'Practice',
    subjectId: 'sub-sci',
    subjectName: 'Science',
    teacherId: 'stf-002',
    teacherName: 'Arjun Mehta',
    classGradeId: 'cls-9',
    classGradeName: 'Grade 9',
    sectionId: 'sec-9-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-02',
    dueDate: '2026-07-09',
    status: 'Published',
    priority: 'High',
    estimatedDurationMinutes: 75,
    totalStudents: 10,
    submissionCount: 8,
    reviewedCount: 5,
    attachmentCount: 1,
    tags: ['Physics', 'Numericals', 'Board Prep'],
    instructions: 'Show all steps. Use proper units. Box your final answers.',
    createdAt: '2026-07-02T10:00:00Z',
    updatedAt: '2026-07-08T11:00:00Z',
  },
  {
    id: 'task-008',
    title: 'Art Activity - Still Life Drawing',
    description: 'Create a still life drawing of the fruit basket setup. Use pencil shading techniques.',
    taskType: 'Activity',
    subjectId: 'sub-art',
    subjectName: 'Art',
    teacherId: 'stf-010',
    teacherName: 'Meera Kapoor',
    classGradeId: 'cls-7',
    classGradeName: 'Grade 7',
    sectionId: 'sec-7-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-05',
    dueDate: '2026-07-08',
    status: 'Due Today',
    priority: 'Low',
    estimatedDurationMinutes: 60,
    totalStudents: 15,
    submissionCount: 10,
    reviewedCount: 6,
    attachmentCount: 0,
    tags: ['Art', 'Drawing', 'Creative'],
    instructions: 'Submit your drawing in person during the next class. Ensure proper lighting in your reference photo.',
    createdAt: '2026-07-05T11:00:00Z',
    updatedAt: '2026-07-07T16:00:00Z',
  },
  {
    id: 'task-009',
    title: 'History Project - Indian Independence Movement',
    description: 'Research and prepare a presentation on one aspect of the Indian Independence Movement.',
    taskType: 'Project',
    subjectId: 'sub-ss',
    subjectName: 'Social Studies',
    teacherId: 'stf-004',
    teacherName: 'Ananya Reddy',
    classGradeId: 'cls-10',
    classGradeName: 'Grade 10',
    sectionId: 'sec-10-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-01',
    dueDate: '2026-07-15',
    status: 'In Progress',
    priority: 'High',
    estimatedDurationMinutes: 180,
    totalStudents: 10,
    submissionCount: 0,
    reviewedCount: 0,
    attachmentCount: 2,
    tags: ['History', 'Project', 'Research'],
    instructions: 'Form groups of 3. Presentation should be 10-15 minutes. Include at least 5 primary sources.',
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-05T09:00:00Z',
  },
  {
    id: 'task-010',
    title: 'Chemistry Revision - Periodic Table',
    description: 'Revise Chapter 2 on Periodic Table. Prepare for the surprise test next week.',
    taskType: 'Revision',
    subjectId: 'sub-sci',
    subjectName: 'Science',
    teacherId: 'stf-002',
    teacherName: 'Arjun Mehta',
    classGradeId: 'cls-8',
    classGradeName: 'Grade 8',
    sectionId: 'sec-8-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-06',
    dueDate: '2026-07-14',
    status: 'Published',
    priority: 'Medium',
    estimatedDurationMinutes: 45,
    totalStudents: 12,
    submissionCount: 0,
    reviewedCount: 0,
    attachmentCount: 1,
    tags: ['Chemistry', 'Revision', 'Test Prep'],
    instructions: 'No submission required. Study all elements up to atomic number 30.',
    createdAt: '2026-07-06T11:00:00Z',
    updatedAt: '2026-07-06T11:00:00Z',
  },
  {
    id: 'task-011',
    title: 'Mathematics Assignment - Trigonometry Basics',
    description: 'Complete the introductory trigonometry assignment covering SOH-CAH-TOA applications.',
    taskType: 'Assignment',
    subjectId: 'sub-math',
    subjectName: 'Mathematics',
    teacherId: 'stf-001',
    teacherName: 'Rebecca Thomas',
    classGradeId: 'cls-9',
    classGradeName: 'Grade 9',
    sectionId: 'sec-9-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-04',
    dueDate: '2026-07-08',
    status: 'Due Today',
    priority: 'High',
    estimatedDurationMinutes: 50,
    totalStudents: 10,
    submissionCount: 9,
    reviewedCount: 6,
    attachmentCount: 1,
    tags: ['Trigonometry', 'Assignment', 'Foundation'],
    instructions: 'Show all calculations. Round answers to 2 decimal places.',
    createdAt: '2026-07-04T08:00:00Z',
    updatedAt: '2026-07-08T07:00:00Z',
  },
  {
    id: 'task-012',
    title: 'English Creative Writing - My Summer Vacation',
    description: 'Write a 500-word essay about your summer vacation experiences. Use descriptive language.',
    taskType: 'Homework',
    subjectId: 'sub-eng',
    subjectName: 'English',
    teacherId: 'stf-003',
    teacherName: 'Lakshmi Iyer',
    classGradeId: 'cls-7',
    classGradeName: 'Grade 7',
    sectionId: 'sec-7-a',
    sectionName: 'A',
    campusId: 'camp-002',
    campusName: 'Greenfield Whitefield Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-01',
    dueDate: '2026-07-06',
    status: 'Closed',
    priority: 'Low',
    estimatedDurationMinutes: 40,
    totalStudents: 15,
    submissionCount: 15,
    reviewedCount: 15,
    attachmentCount: 0,
    tags: ['Writing', 'Creative', 'Essay'],
    instructions: 'Use at least 3 descriptive adjectives and 2 metaphors.',
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-07-07T10:00:00Z',
  },
  {
    id: 'task-013',
    title: 'Biology Diagram Practice - Cell Structure',
    description: 'Draw and label the structure of a plant cell and an animal cell with all organelles.',
    taskType: 'Practice',
    subjectId: 'sub-sci',
    subjectName: 'Science',
    teacherId: 'stf-002',
    teacherName: 'Arjun Mehta',
    classGradeId: 'cls-8',
    classGradeName: 'Grade 8',
    sectionId: 'sec-8-b',
    sectionName: 'B',
    campusId: 'camp-002',
    campusName: 'Greenfield Whitefield Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-05',
    dueDate: '2026-07-12',
    status: 'Published',
    priority: 'Medium',
    estimatedDurationMinutes: 35,
    totalStudents: 10,
    submissionCount: 4,
    reviewedCount: 1,
    attachmentCount: 1,
    tags: ['Biology', 'Diagrams', 'Practice'],
    instructions: 'Use colored pencils. Label at least 10 organelles for each cell type.',
    createdAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-07-07T14:00:00Z',
  },
  {
    id: 'task-014',
    title: 'Hindi Reading - Premchand ki Kahaniyan',
    description: 'Read "Idgah" by Munshi Premchand and write a summary in Hindi.',
    taskType: 'Reading',
    subjectId: 'sub-hindi',
    subjectName: 'Hindi',
    teacherId: 'stf-012',
    teacherName: 'Deepa Venkatesh',
    classGradeId: 'cls-10',
    classGradeName: 'Grade 10',
    sectionId: 'sec-10-b',
    sectionName: 'B',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-02',
    dueDate: '2026-07-09',
    status: 'Published',
    priority: 'Medium',
    estimatedDurationMinutes: 50,
    totalStudents: 8,
    submissionCount: 6,
    reviewedCount: 4,
    attachmentCount: 1,
    tags: ['Literature', 'Premchand', 'Reading'],
    instructions: 'Write your summary in 200 words. Express the central theme in your own words.',
    createdAt: '2026-07-02T09:00:00Z',
    updatedAt: '2026-07-07T15:00:00Z',
  },
  {
    id: 'task-015',
    title: 'Draft: Science Fair Project Proposal',
    description: 'Prepare a draft proposal for your science fair project including hypothesis and methodology.',
    taskType: 'Project',
    subjectId: 'sub-sci',
    subjectName: 'Science',
    teacherId: 'stf-002',
    teacherName: 'Arjun Mehta',
    classGradeId: 'cls-9',
    classGradeName: 'Grade 9',
    sectionId: 'sec-9-b',
    sectionName: 'B',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-07',
    dueDate: '2026-07-20',
    status: 'Draft',
    priority: 'Medium',
    estimatedDurationMinutes: 60,
    totalStudents: 0,
    submissionCount: 0,
    reviewedCount: 0,
    attachmentCount: 0,
    tags: ['Science Fair', 'Project', 'Research'],
    instructions: 'Draft proposal not yet published to students.',
    createdAt: '2026-07-07T14:00:00Z',
    updatedAt: '2026-07-07T14:00:00Z',
  },
  {
    id: 'task-016',
    title: 'Mathematics Chapter Test Practice',
    description: 'Practice problems from previous years\' board exam papers on Polynomials.',
    taskType: 'Revision',
    subjectId: 'sub-math',
    subjectName: 'Mathematics',
    teacherId: 'stf-011',
    teacherName: 'Vikram Rao',
    classGradeId: 'cls-8',
    classGradeName: 'Grade 8',
    sectionId: 'sec-8-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-06',
    dueDate: '2026-07-08',
    status: 'Due Today',
    priority: 'High',
    estimatedDurationMinutes: 45,
    totalStudents: 12,
    submissionCount: 10,
    reviewedCount: 8,
    attachmentCount: 2,
    tags: ['Polynomials', 'Board Prep', 'Practice'],
    instructions: 'Attempt at least 20 problems. Mark difficult ones for discussion.',
    createdAt: '2026-07-06T08:00:00Z',
    updatedAt: '2026-07-08T10:00:00Z',
  },
  {
    id: 'task-017',
    title: 'Geography Weather Journal',
    description: 'Record weather data for 7 consecutive days including temperature, humidity, and cloud cover.',
    taskType: 'Activity',
    subjectId: 'sub-ss',
    subjectName: 'Social Studies',
    teacherId: 'stf-004',
    teacherName: 'Ananya Reddy',
    classGradeId: 'cls-7',
    classGradeName: 'Grade 7',
    sectionId: 'sec-7-b',
    sectionName: 'B',
    campusId: 'camp-002',
    campusName: 'Greenfield Whitefield Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-01',
    dueDate: '2026-07-08',
    status: 'Due Today',
    priority: 'Low',
    estimatedDurationMinutes: 10,
    totalStudents: 14,
    submissionCount: 14,
    reviewedCount: 10,
    attachmentCount: 0,
    tags: ['Weather', 'Observation', 'Journal'],
    instructions: 'Use the weather app or local news. Create a bar chart for temperature.',
    createdAt: '2026-07-01T12:00:00Z',
    updatedAt: '2026-07-08T11:00:00Z',
  },
  {
    id: 'task-018',
    title: 'English Vocabulary Building',
    description: 'Learn 20 new vocabulary words from the provided list. Use each in a sentence.',
    taskType: 'Homework',
    subjectId: 'sub-eng',
    subjectName: 'English',
    teacherId: 'stf-003',
    teacherName: 'Lakshmi Iyer',
    classGradeId: 'cls-9',
    classGradeName: 'Grade 9',
    sectionId: 'sec-9-b',
    sectionName: 'B',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-04',
    dueDate: '2026-07-06',
    status: 'Archived',
    priority: 'Low',
    estimatedDurationMinutes: 25,
    totalStudents: 8,
    submissionCount: 8,
    reviewedCount: 8,
    attachmentCount: 1,
    tags: ['Vocabulary', 'Language', 'Practice'],
    instructions: 'Write sentences showing correct usage. Underline the target word.',
    createdAt: '2026-07-04T10:00:00Z',
    updatedAt: '2026-07-07T09:00:00Z',
  },
  {
    id: 'task-019',
    title: 'Computer Science Project Documentation',
    description: 'Prepare documentation for your semester project including user manual and technical specifications.',
    taskType: 'Project',
    subjectId: 'sub-cs',
    subjectName: 'Computer Science',
    teacherId: 'stf-008',
    teacherName: 'Rajesh Nair',
    classGradeId: 'cls-10',
    classGradeName: 'Grade 10',
    sectionId: 'sec-10-b',
    sectionName: 'B',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-01',
    dueDate: '2026-07-22',
    status: 'Scheduled',
    priority: 'Critical',
    estimatedDurationMinutes: 120,
    totalStudents: 8,
    submissionCount: 0,
    reviewedCount: 0,
    attachmentCount: 1,
    tags: ['Documentation', 'Project', 'Technical'],
    instructions: 'Task will be published on July 10th. Prepare documentation templates in advance.',
    createdAt: '2026-07-01T14:00:00Z',
    updatedAt: '2026-07-01T14:00:00Z',
  },
  {
    id: 'task-020',
    title: 'Physical Education Fitness Log',
    description: 'Track your daily physical activities for one week. Include duration and type of exercise.',
    taskType: 'Activity',
    subjectId: 'sub-pe',
    subjectName: 'Physical Education',
    teacherId: 'stf-009',
    teacherName: 'Suresh Kumar',
    classGradeId: 'cls-8',
    classGradeName: 'Grade 8',
    sectionId: 'sec-8-a',
    sectionName: 'A',
    campusId: 'camp-001',
    campusName: 'Greenfield Main Campus',
    academicYearId: 'ay-2026-27',
    academicYearName: 'Academic Year 2026-27',
    assignedDate: '2026-07-02',
    dueDate: '2026-07-09',
    status: 'Published',
    priority: 'Low',
    estimatedDurationMinutes: 15,
    totalStudents: 12,
    submissionCount: 5,
    reviewedCount: 2,
    attachmentCount: 0,
    tags: ['Fitness', 'Health', 'Activity'],
    instructions: 'Include at least 3 different types of exercise. Reflect on how exercise affects your mood.',
    createdAt: '2026-07-02T11:00:00Z',
    updatedAt: '2026-07-07T10:00:00Z',
  },
];

// Homework Attachments (24)
export const homeworkAttachments: HomeworkAttachment[] = [
  { id: 'att-001', taskId: 'task-001', name: 'Reading_Chapter5.pdf', type: 'Document', url: '#reading-ch5', sizeLabel: '2.4 MB', uploadedBy: 'Lakshmi Iyer', uploadedAt: '2026-07-01T09:00:00Z' },
  { id: 'att-002', taskId: 'task-002', name: 'Quadratic_Worksheet.pdf', type: 'Worksheet', url: '#quadratic-ws', sizeLabel: '1.1 MB', uploadedBy: 'Rebecca Thomas', uploadedAt: '2026-07-03T08:00:00Z' },
  { id: 'att-003', taskId: 'task-003', name: 'Lab_Template.docx', type: 'Document', url: '#lab-template', sizeLabel: '45 KB', uploadedBy: 'Arjun Mehta', uploadedAt: '2026-07-01T11:00:00Z' },
  { id: 'att-004', taskId: 'task-003', name: 'Photosynthesis_Diagram.jpg', type: 'Image', url: '#photo-diagram', sizeLabel: '890 KB', uploadedBy: 'Arjun Mehta', uploadedAt: '2026-07-01T11:05:00Z' },
  { id: 'att-005', taskId: 'task-004', name: 'India_Blank_Map.pdf', type: 'Worksheet', url: '#india-map', sizeLabel: '3.2 MB', uploadedBy: 'Ananya Reddy', uploadedAt: '2026-07-05T10:00:00Z' },
  { id: 'att-006', taskId: 'task-005', name: 'Sandhi_Rules.pdf', type: 'Reference', url: '#sandhi-rules', sizeLabel: '560 KB', uploadedBy: 'Deepa Venkatesh', uploadedAt: '2026-07-04T08:30:00Z' },
  { id: 'att-007', taskId: 'task-006', name: 'Python_Loops_Problems.pdf', type: 'Worksheet', url: '#python-loops', sizeLabel: '780 KB', uploadedBy: 'Rajesh Nair', uploadedAt: '2026-07-06T09:00:00Z' },
  { id: 'att-008', taskId: 'task-007', name: 'Newton_Laws_Numericals.pdf', type: 'Worksheet', url: '#newton-num', sizeLabel: '1.5 MB', uploadedBy: 'Arjun Mehta', uploadedAt: '2026-07-02T10:00:00Z' },
  { id: 'att-009', taskId: 'task-009', name: 'Project_Guidelines.pdf', type: 'Document', url: '#project-guide', sizeLabel: '2.1 MB', uploadedBy: 'Ananya Reddy', uploadedAt: '2026-07-01T10:00:00Z' },
  { id: 'att-010', taskId: 'task-009', name: 'Primary_Sources_List.xlsx', type: 'Document', url: '#sources-list', sizeLabel: '340 KB', uploadedBy: 'Ananya Reddy', uploadedAt: '2026-07-01T10:05:00Z' },
  { id: 'att-011', taskId: 'task-010', name: 'Periodic_Table_Summary.pdf', type: 'Reference', url: '#periodic-summary', sizeLabel: '1.8 MB', uploadedBy: 'Arjun Mehta', uploadedAt: '2026-07-06T11:00:00Z' },
  { id: 'att-012', taskId: 'task-011', name: 'Trigonometry_Basics.pdf', type: 'Worksheet', url: '#trig-basics', sizeLabel: '920 KB', uploadedBy: 'Rebecca Thomas', uploadedAt: '2026-07-04T08:00:00Z' },
  { id: 'att-013', taskId: 'task-013', name: 'Cell_Structure_Template.pdf', type: 'Worksheet', url: '#cell-template', sizeLabel: '450 KB', uploadedBy: 'Arjun Mehta', uploadedAt: '2026-07-05T10:00:00Z' },
  { id: 'att-014', taskId: 'task-014', name: 'Idgah_Full_Story.pdf', type: 'Document', url: '#idgah-story', sizeLabel: '180 KB', uploadedBy: 'Deepa Venkatesh', uploadedAt: '2026-07-02T09:00:00Z' },
  { id: 'att-015', taskId: 'task-016', name: 'Board_Papers_Polynomials.pdf', type: 'Worksheet', url: '#board-poly', sizeLabel: '4.2 MB', uploadedBy: 'Vikram Rao', uploadedAt: '2026-07-06T08:00:00Z' },
  { id: 'att-016', taskId: 'task-016', name: 'Polynomials_Solutions.pdf', type: 'Reference', url: '#poly-solutions', sizeLabel: '2.8 MB', uploadedBy: 'Vikram Rao', uploadedAt: '2026-07-06T08:05:00Z' },
  { id: 'att-017', taskId: 'task-018', name: 'Vocabulary_List.pdf', type: 'Document', url: '#vocab-list', sizeLabel: '120 KB', uploadedBy: 'Lakshmi Iyer', uploadedAt: '2026-07-04T10:00:00Z' },
  { id: 'att-018', taskId: 'task-019', name: 'Documentation_Template.docx', type: 'Document', url: '#doc-template', sizeLabel: '85 KB', uploadedBy: 'Rajesh Nair', uploadedAt: '2026-07-01T14:00:00Z' },
  { id: 'att-019', taskId: 'task-001', name: 'Sample_Response.docx', type: 'Reference', url: '#sample-resp', sizeLabel: '35 KB', uploadedBy: 'Lakshmi Iyer', uploadedAt: '2026-07-02T09:00:00Z' },
  { id: 'att-020', taskId: 'task-002', name: 'Video_Tutorial_Link', type: 'Link', url: 'https://example.com/quadratic-video', sizeLabel: '-', uploadedBy: 'Rebecca Thomas', uploadedAt: '2026-07-03T08:30:00Z' },
  { id: 'att-021', taskId: 'task-006', name: 'Python_Docs_Link', type: 'Link', url: 'https://docs.python.org/3/tutorial/controlflow.html', sizeLabel: '-', uploadedBy: 'Rajesh Nair', uploadedAt: '2026-07-06T09:15:00Z' },
  { id: 'att-022', taskId: 'task-007', name: 'Newton_Laws_Video', type: 'Link', url: 'https://example.com/newton-laws', sizeLabel: '-', uploadedBy: 'Arjun Mehta', uploadedAt: '2026-07-02T10:30:00Z' },
  { id: 'att-023', taskId: 'task-011', name: 'Trig_Cheat_Sheet.pdf', type: 'Reference', url: '#trig-cheat', sizeLabel: '220 KB', uploadedBy: 'Rebecca Thomas', uploadedAt: '2026-07-04T08:15:00Z' },
  { id: 'att-024', taskId: 'task-014', name: 'Premchand_Biography.pdf', type: 'Reference', url: '#premchand-bio', sizeLabel: '340 KB', uploadedBy: 'Deepa Venkatesh', uploadedAt: '2026-07-02T09:15:00Z' },
];

// Homework Audience (20)
export const homeworkAudiences: HomeworkAudience[] = [
  { id: 'aud-001', taskId: 'task-001', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', totalStudents: 10, activeStudents: 10 },
  { id: 'aud-002', taskId: 'task-002', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', totalStudents: 10, activeStudents: 10 },
  { id: 'aud-003', taskId: 'task-003', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', totalStudents: 8, activeStudents: 8 },
  { id: 'aud-004', taskId: 'task-004', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-a', sectionName: 'A', totalStudents: 12, activeStudents: 12 },
  { id: 'aud-005', taskId: 'task-005', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', totalStudents: 10, activeStudents: 10 },
  { id: 'aud-006', taskId: 'task-006', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', totalStudents: 10, activeStudents: 10 },
  { id: 'aud-007', taskId: 'task-007', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', totalStudents: 10, activeStudents: 10 },
  { id: 'aud-008', taskId: 'task-008', classGradeId: 'cls-7', classGradeName: 'Grade 7', sectionId: 'sec-7-a', sectionName: 'A', totalStudents: 15, activeStudents: 15 },
  { id: 'aud-009', taskId: 'task-009', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', totalStudents: 10, activeStudents: 10 },
  { id: 'aud-010', taskId: 'task-010', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-a', sectionName: 'A', totalStudents: 12, activeStudents: 12 },
  { id: 'aud-011', taskId: 'task-011', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', totalStudents: 10, activeStudents: 9 },
  { id: 'aud-012', taskId: 'task-012', classGradeId: 'cls-7', classGradeName: 'Grade 7', sectionId: 'sec-7-a', sectionName: 'A', totalStudents: 15, activeStudents: 15 },
  { id: 'aud-013', taskId: 'task-013', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-b', sectionName: 'B', totalStudents: 10, activeStudents: 10 },
  { id: 'aud-014', taskId: 'task-014', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', totalStudents: 8, activeStudents: 8 },
  { id: 'aud-015', taskId: 'task-016', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-a', sectionName: 'A', totalStudents: 12, activeStudents: 11 },
  { id: 'aud-016', taskId: 'task-017', classGradeId: 'cls-7', classGradeName: 'Grade 7', sectionId: 'sec-7-b', sectionName: 'B', totalStudents: 14, activeStudents: 14 },
  { id: 'aud-017', taskId: 'task-018', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-b', sectionName: 'B', totalStudents: 8, activeStudents: 8 },
  { id: 'aud-018', taskId: 'task-019', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', totalStudents: 8, activeStudents: 8 },
  { id: 'aud-019', taskId: 'task-020', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-a', sectionName: 'A', totalStudents: 12, activeStudents: 12 },
  { id: 'aud-020', taskId: 'task-003', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', totalStudents: 10, activeStudents: 10 },
];

// Homework Submissions (60)
export const homeworkSubmissions: HomeworkSubmission[] = [];

const studentPoolHW = [
  { id: 'stu-001', name: 'Aarav Sharma', admission: 'ADM2024001', roll: '10A001' },
  { id: 'stu-002', name: 'Ananya Patel', admission: 'ADM2024002', roll: '10A002' },
  { id: 'stu-003', name: 'Arjun Nair', admission: 'ADM2024003', roll: '10A003' },
  { id: 'stu-004', name: 'Diya Reddy', admission: 'ADM2024004', roll: '10A004' },
  { id: 'stu-005', name: 'Ishaan Gupta', admission: 'ADM2024005', roll: '10A005' },
  { id: 'stu-006', name: 'Kavya Iyer', admission: 'ADM2024006', roll: '10A006' },
  { id: 'stu-007', name: 'Rohan Kumar', admission: 'ADM2024007', roll: '10A007' },
  { id: 'stu-008', name: 'Saanvi Menon', admission: 'ADM2024008', roll: '10A008' },
  { id: 'stu-009', name: 'Vihaan Singh', admission: 'ADM2024009', roll: '10A009' },
  { id: 'stu-010', name: 'Zara Khan', admission: 'ADM2024010', roll: '10A010' },
];

const submissionStatusOptions: HomeworkSubmission['status'][] = ['Submitted', 'Submitted', 'Submitted', 'Late Submission', 'Not Submitted'];
const reviewStatusOptions: HomeworkSubmission['reviewStatus'][] = ['Reviewed', 'Reviewed', 'In Review', 'Not Reviewed', 'Rework Required'];

let submissionId = 1;
for (let tIdx = 0; tIdx < 6; tIdx++) {
  const task = homeworkTasks[tIdx];
  for (let sIdx = 0; sIdx < 10; sIdx++) {
    const student = studentPoolHW[sIdx];
    const submitted = sIdx < task.submissionCount;
    const reviewed = sIdx < task.reviewedCount;

    homeworkSubmissions.push({
      id: `subm-${String(submissionId).padStart(3, '0')}`,
      taskId: task.id,
      studentId: student.id,
      studentName: student.name,
      admissionNumber: student.admission,
      rollNumber: student.roll,
      submittedAt: submitted ? `2026-07-0${7 - Math.floor(sIdx / 3)}T${14 + (sIdx % 10)}:00:00Z` : null,
      status: submitted ? (sIdx === task.submissionCount - 1 ? 'Late Submission' : 'Submitted') : 'Not Submitted',
      reviewStatus: reviewed ? 'Reviewed' : (submitted ? 'Not Reviewed' : 'Not Reviewed'),
      submissionText: submitted ? `Submission for ${task.title} by ${student.name}` : null,
      attachmentCount: submitted ? Math.floor(Math.random() * 3) : 0,
      lateByMinutes: submitted && sIdx === task.submissionCount - 1 ? Math.floor(Math.random() * 120) + 30 : null,
      marksAwarded: reviewed ? Math.floor(Math.random() * 20) + 5 : null,
      feedbackSnippet: reviewed ? `Good work on ${task.subjectName}. Keep practicing.` : null,
    });
    submissionId++;
  }
}

// Homework Reviews (30)
export const homeworkReviews: HomeworkReview[] = [];
let reviewId = 1;

for (let i = 0; i < 30; i++) {
  const submission = homeworkSubmissions[i];
  const isReviewed = submission.reviewStatus === 'Reviewed';
  const task = homeworkTasks.find((t) => t.id === submission.taskId);

  homeworkReviews.push({
    id: `rev-${String(reviewId).padStart(3, '0')}`,
    submissionId: submission.id,
    reviewedBy: task?.teacherName || 'Teacher',
    reviewedAt: isReviewed ? `2026-07-08T${10 + (i % 8)}:00:00Z` : null,
    reviewStatus: submission.reviewStatus,
    feedback: isReviewed ? `Feedback for ${submission.studentName}'s submission on ${task?.title}` : null,
    actionRequired: submission.reviewStatus === 'Rework Required' ? 'Please resubmit with corrections' : null,
  });
  reviewId++;
}

// Homework Class Summaries (10)
export const homeworkClassSummaries: HomeworkClassSummary[] = [
  { id: 'hcs-001', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', activeTasks: 5, dueToday: 2, overdue: 1, submissionRate: 72, reviewRate: 54 },
  { id: 'hcs-002', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', activeTasks: 3, dueToday: 0, overdue: 1, submissionRate: 65, reviewRate: 42 },
  { id: 'hcs-003', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-a', sectionName: 'A', activeTasks: 4, dueToday: 2, overdue: 0, submissionRate: 80, reviewRate: 65 },
  { id: 'hcs-004', classGradeId: 'cls-9', classGradeName: 'Grade 9', sectionId: 'sec-9-b', sectionName: 'B', activeTasks: 2, dueToday: 0, overdue: 0, submissionRate: 88, reviewRate: 75 },
  { id: 'hcs-005', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-a', sectionName: 'A', activeTasks: 6, dueToday: 3, overdue: 0, submissionRate: 78, reviewRate: 58 },
  { id: 'hcs-006', classGradeId: 'cls-8', classGradeName: 'Grade 8', sectionId: 'sec-8-b', sectionName: 'B', activeTasks: 3, dueToday: 0, overdue: 0, submissionRate: 70, reviewRate: 50 },
  { id: 'hcs-007', classGradeId: 'cls-7', classGradeName: 'Grade 7', sectionId: 'sec-7-a', sectionName: 'A', activeTasks: 4, dueToday: 2, overdue: 0, submissionRate: 85, reviewRate: 70 },
  { id: 'hcs-008', classGradeId: 'cls-7', classGradeName: 'Grade 7', sectionId: 'sec-7-b', sectionName: 'B', activeTasks: 2, dueToday: 1, overdue: 0, submissionRate: 92, reviewRate: 80 },
  { id: 'hcs-009', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-a', sectionName: 'A', activeTasks: 5, dueToday: 2, overdue: 1, submissionRate: 72, reviewRate: 54 },
  { id: 'hcs-010', classGradeId: 'cls-10', classGradeName: 'Grade 10', sectionId: 'sec-10-b', sectionName: 'B', activeTasks: 3, dueToday: 0, overdue: 1, submissionRate: 68, reviewRate: 48 },
];

// Homework Subject Summaries (8)
export const homeworkSubjectSummaries: HomeworkSubjectSummary[] = [
  { id: 'hss-001', subjectId: 'sub-math', subjectName: 'Mathematics', activeTasks: 4, totalSubmissions: 28, pendingReviews: 8, completionRate: 75 },
  { id: 'hss-002', subjectId: 'sub-eng', subjectName: 'English', activeTasks: 3, totalSubmissions: 24, pendingReviews: 5, completionRate: 82 },
  { id: 'hss-003', subjectId: 'sub-sci', subjectName: 'Science', activeTasks: 5, totalSubmissions: 35, pendingReviews: 12, completionRate: 70 },
  { id: 'hss-004', subjectId: 'sub-ss', subjectName: 'Social Studies', activeTasks: 3, totalSubmissions: 18, pendingReviews: 4, completionRate: 88 },
  { id: 'hss-005', subjectId: 'sub-hindi', subjectName: 'Hindi', activeTasks: 2, totalSubmissions: 14, pendingReviews: 3, completionRate: 80 },
  { id: 'hss-006', subjectId: 'sub-cs', subjectName: 'Computer Science', activeTasks: 2, totalSubmissions: 8, pendingReviews: 2, completionRate: 65 },
  { id: 'hss-007', subjectId: 'sub-art', subjectName: 'Art', activeTasks: 1, totalSubmissions: 10, pendingReviews: 4, completionRate: 90 },
  { id: 'hss-008', subjectId: 'sub-pe', subjectName: 'Physical Education', activeTasks: 1, totalSubmissions: 5, pendingReviews: 2, completionRate: 95 },
];

// Homework Student Progress (12)
export const homeworkStudentProgress: HomeworkStudentProgress[] = [
  { id: 'hsp-001', studentId: 'stu-001', studentName: 'Aarav Sharma', classGradeName: 'Grade 10', sectionName: 'A', assignedTasks: 8, submittedTasks: 8, pendingTasks: 0, overdueTasks: 0, reviewedTasks: 6, completionPercentage: 100 },
  { id: 'hsp-002', studentId: 'stu-002', studentName: 'Ananya Patel', classGradeName: 'Grade 10', sectionName: 'A', assignedTasks: 8, submittedTasks: 7, pendingTasks: 1, overdueTasks: 0, reviewedTasks: 5, completionPercentage: 88 },
  { id: 'hsp-003', studentId: 'stu-003', studentName: 'Arjun Nair', classGradeName: 'Grade 10', sectionName: 'A', assignedTasks: 8, submittedTasks: 6, pendingTasks: 2, overdueTasks: 1, reviewedTasks: 4, completionPercentage: 75 },
  { id: 'hsp-004', studentId: 'stu-004', studentName: 'Diya Reddy', classGradeName: 'Grade 10', sectionName: 'A', assignedTasks: 8, submittedTasks: 8, pendingTasks: 0, overdueTasks: 0, reviewedTasks: 7, completionPercentage: 100 },
  { id: 'hsp-005', studentId: 'stu-005', studentName: 'Ishaan Gupta', classGradeName: 'Grade 10', sectionName: 'A', assignedTasks: 8, submittedTasks: 5, pendingTasks: 3, overdueTasks: 2, reviewedTasks: 3, completionPercentage: 63 },
  { id: 'hsp-006', studentId: 'stu-006', studentName: 'Kavya Iyer', classGradeName: 'Grade 10', sectionName: 'A', assignedTasks: 8, submittedTasks: 7, pendingTasks: 1, overdueTasks: 0, reviewedTasks: 5, completionPercentage: 88 },
  { id: 'hsp-007', studentId: 'stu-007', studentName: 'Rohan Kumar', classGradeName: 'Grade 10', sectionName: 'A', assignedTasks: 8, submittedTasks: 6, pendingTasks: 2, overdueTasks: 1, reviewedTasks: 4, completionPercentage: 75 },
  { id: 'hsp-008', studentId: 'stu-008', studentName: 'Saanvi Menon', classGradeName: 'Grade 10', sectionName: 'A', assignedTasks: 8, submittedTasks: 8, pendingTasks: 0, overdueTasks: 0, reviewedTasks: 6, completionPercentage: 100 },
  { id: 'hsp-009', studentId: 'stu-009', studentName: 'Vihaan Singh', classGradeName: 'Grade 10', sectionName: 'A', assignedTasks: 8, submittedTasks: 4, pendingTasks: 4, overdueTasks: 2, reviewedTasks: 2, completionPercentage: 50 },
  { id: 'hsp-010', studentId: 'stu-010', studentName: 'Zara Khan', classGradeName: 'Grade 10', sectionName: 'A', assignedTasks: 8, submittedTasks: 7, pendingTasks: 1, overdueTasks: 0, reviewedTasks: 5, completionPercentage: 88 },
  { id: 'hsp-011', studentId: 'stu-011', studentName: 'Aditya Verma', classGradeName: 'Grade 9', sectionName: 'A', assignedTasks: 6, submittedTasks: 5, pendingTasks: 1, overdueTasks: 0, reviewedTasks: 4, completionPercentage: 83 },
  { id: 'hsp-012', studentId: 'stu-012', studentName: 'Bhavya Joshi', classGradeName: 'Grade 9', sectionName: 'A', assignedTasks: 6, submittedTasks: 6, pendingTasks: 0, overdueTasks: 0, reviewedTasks: 5, completionPercentage: 100 },
];

// Homework Alerts (8)
export const homeworkAlerts: HomeworkAlert[] = [
  { id: 'ha-001', title: 'Overdue Tasks Alert', description: '3 tasks are overdue in Grade 10 - Science Lab Observation pending from 2 students', severity: 'Critical', date: CURRENT_DATE, relatedEntity: { type: 'task', id: 'task-003', name: 'Science Lab Observation' }, status: 'Active', actionRequired: 'Follow up with students immediately' },
  { id: 'ha-002', title: 'High Priority Due Today', description: '2 high-priority tasks due today require attention: Mathematics Trigonometry, English Reading', severity: 'Warning', date: CURRENT_DATE, relatedEntity: { type: 'class', id: 'cls-10', name: 'Grade 10' }, status: 'Active', actionRequired: 'Monitor submission progress' },
  { id: 'ha-003', title: 'Pending Reviews Backlog', description: '15 submissions awaiting review across subjects. Oldest pending for 3 days.', severity: 'Warning', date: CURRENT_DATE, relatedEntity: { type: 'review', id: 'reviews', name: 'Pending Reviews' }, status: 'Active', actionRequired: 'Teachers to prioritize review queue' },
  { id: 'ha-004', title: 'Project Milestone Approaching', description: 'History Independence Project draft review due in 5 days for Grade 10A', severity: 'Info', date: CURRENT_DATE, relatedEntity: { type: 'task', id: 'task-009', name: 'History Project' }, status: 'Active', actionRequired: null },
  { id: 'ha-005', title: 'Low Completion Rate Alert', description: 'Computer Science Coding Exercise shows 10% completion rate. Only 1 of 10 students submitted.', severity: 'Warning', date: CURRENT_DATE, relatedEntity: { type: 'task', id: 'task-006', name: 'Coding Exercise' }, status: 'Active', actionRequired: 'Check if students need additional support' },
  { id: 'ha-006', title: 'Task Scheduled for Publishing', description: 'Computer Science Project Documentation scheduled to publish on July 10th', severity: 'Info', date: CURRENT_DATE, relatedEntity: { type: 'task', id: 'task-019', name: 'CS Project Documentation' }, status: 'Active', actionRequired: null },
  { id: 'ha-007', title: 'Submission Deadline Reminder', description: 'Mathematics Quadratic Equations worksheet due in 2 days for Grade 10A', severity: 'Info', date: CURRENT_DATE, relatedEntity: { type: 'task', id: 'task-002', name: 'Quadratic Equations' }, status: 'Active', actionRequired: null },
  { id: 'ha-008', title: 'Late Submission Spike', description: '4 late submissions recorded this week across Grade 10, compared to 1 last week', severity: 'Warning', date: CURRENT_DATE, relatedEntity: { type: 'class', id: 'cls-10', name: 'Grade 10' }, status: 'Active', actionRequired: 'Review late submission policy with students' },
];

// Homework Activity Events (12)
export const homeworkActivityEvents: HomeworkActivityEvent[] = [
  { id: 'hae-001', eventType: 'Task Created', title: 'Science Lab Observation created', description: 'Lab observation task created for Grade 10B Science class', actor: 'Arjun Mehta', timestamp: '2026-07-01T11:00:00Z', severity: 'Info', relatedEntity: { type: 'task', id: 'task-003', name: 'Science Lab Observation' } },
  { id: 'hae-002', eventType: 'Task Published', title: 'Reading Response published', description: 'English Reading Response Chapter 5 published for Grade 10A', actor: 'Lakshmi Iyer', timestamp: '2026-07-01T09:05:00Z', severity: 'Info', relatedEntity: { type: 'task', id: 'task-001', name: 'Reading Response' } },
  { id: 'hae-003', eventType: 'Submission Received', title: 'Aarav Sharma submitted Trigonometry', description: 'Submission received for Mathematics Trigonometry assignment', actor: 'Aarav Sharma', timestamp: '2026-07-07T16:30:00Z', severity: 'Info', relatedEntity: { type: 'submission', id: 'subm-041', name: 'Trigonometry Assignment' } },
  { id: 'hae-004', eventType: 'Review Completed', title: 'Worksheet reviewed', description: 'Mathematics Quadratic Equations worksheet submissions reviewed', actor: 'Rebecca Thomas', timestamp: '2026-07-07T14:00:00Z', severity: 'Info', relatedEntity: { type: 'review', id: 'rev-025', name: 'Quadratic Worksheet Review' } },
  { id: 'hae-005', eventType: 'Rework Requested', title: 'Rework requested for Hindi assignment', description: 'Rework requested for student submission on Hindi Grammar', actor: 'Deepa Venkatesh', timestamp: '2026-07-06T11:00:00Z', severity: 'Warning', relatedEntity: { type: 'submission', id: 'subm-032', name: 'Hindi Grammar' } },
  { id: 'hae-006', eventType: 'Task Overdue Alert', title: 'Science Lab Observation overdue', description: 'Science Lab Observation task marked overdue - 3 students yet to submit', actor: 'System', timestamp: '2026-07-08T00:00:00Z', severity: 'Warning', relatedEntity: { type: 'task', id: 'task-003', name: 'Lab Observation' } },
  { id: 'hae-007', eventType: 'Task Archived', title: 'English Vocabulary archived', description: 'English Vocabulary Building task archived after completion', actor: 'Lakshmi Iyer', timestamp: '2026-07-07T09:00:00Z', severity: 'Info', relatedEntity: { type: 'task', id: 'task-018', name: 'Vocabulary Building' } },
  { id: 'hae-008', eventType: 'Task Closed', title: 'Summer Vacation essay closed', description: 'My Summer Vacation essay task closed after all submissions reviewed', actor: 'Lakshmi Iyer', timestamp: '2026-07-07T10:00:00Z', severity: 'Info', relatedEntity: { type: 'task', id: 'task-012', name: 'Summer Vacation Essay' } },
  { id: 'hae-009', eventType: 'Submission Received', title: 'Ananya Patel submitted Physics Numericals', description: 'All 15 numericals submitted for Laws of Motion', actor: 'Ananya Patel', timestamp: '2026-07-08T08:15:00Z', severity: 'Info', relatedEntity: { type: 'submission', id: 'subm-020', name: 'Physics Numericals' } },
  { id: 'hae-010', eventType: 'Review Completed', title: 'Art drawings reviewed', description: 'Still Life drawings reviewed for Grade 7A Art class', actor: 'Meera Kapoor', timestamp: '2026-07-07T16:00:00Z', severity: 'Info', relatedEntity: { type: 'review', id: 'rev-006', name: 'Art Review' } },
  { id: 'hae-011', eventType: 'Task Created', title: 'CS Project Documentation drafted', description: 'Computer Science project documentation task drafted for Grade 10B', actor: 'Rajesh Nair', timestamp: '2026-07-01T14:00:00Z', severity: 'Info', relatedEntity: { type: 'task', id: 'task-019', name: 'CS Project Documentation' } },
  { id: 'hae-012', eventType: 'Late Submission Received', title: 'Late submission for Reading Response', description: 'Late submission received from student, 45 minutes past deadline', actor: 'Arjun Nair', timestamp: '2026-07-08T09:45:00Z', severity: 'Warning', relatedEntity: { type: 'submission', id: 'subm-007', name: 'Reading Response' } },
];

// Task Checklist Items (10)
export const taskChecklistItems: TaskChecklistItem[] = [
  { id: 'chk-001', taskId: 'task-009', label: 'Research primary sources', completed: true, owner: 'All Group Members', dueDate: '2026-07-08' },
  { id: 'chk-002', taskId: 'task-009', label: 'Create outline for presentation', completed: true, owner: 'Aarav Sharma', dueDate: '2026-07-10' },
  { id: 'chk-003', taskId: 'task-009', label: 'Draft presentation slides', completed: false, owner: 'Ananya Patel', dueDate: '2026-07-12' },
  { id: 'chk-004', taskId: 'task-009', label: 'Review and finalize presentation', completed: false, owner: 'All Group Members', dueDate: '2026-07-14' },
  { id: 'chk-005', taskId: 'task-019', label: 'Prepare technical specifications document', completed: false, owner: 'Student Team', dueDate: '2026-07-15' },
  { id: 'chk-006', taskId: 'task-019', label: 'Write user manual', completed: false, owner: 'Student Team', dueDate: '2026-07-18' },
  { id: 'chk-007', taskId: 'task-006', label: 'Complete problem 1-3', completed: true, owner: 'All Students', dueDate: '2026-07-10' },
  { id: 'chk-008', taskId: 'task-006', label: 'Complete problem 4-5', completed: false, owner: 'All Students', dueDate: '2026-07-12' },
  { id: 'chk-009', taskId: 'task-001', label: 'Read Chapter 5', completed: true, owner: 'All Students', dueDate: '2026-07-05' },
  { id: 'chk-010', taskId: 'task-001', label: 'Write 300-word analysis', completed: false, owner: 'All Students', dueDate: '2026-07-08' },
];

// Learning Task Templates (8)
export const learningTaskTemplates: LearningTaskTemplate[] = [
  { id: 'tpl-001', name: 'Weekly Reading Response', taskType: 'Reading', subjectName: 'English', suggestedDurationMinutes: 45, recommendedForLevels: ['Grade 7', 'Grade 8', 'Grade 9', 'Grade 10'], instructionsTemplate: 'Read the assigned chapter and write a {word_count}-word response analyzing the key themes, character development, and your personal reflections.', status: 'Active' },
  { id: 'tpl-002', name: 'Mathematics Practice Set', taskType: 'Worksheet', subjectName: 'Mathematics', suggestedDurationMinutes: 60, recommendedForLevels: ['Grade 8', 'Grade 9', 'Grade 10'], instructionsTemplate: 'Solve all problems from Exercise {exercise_number}. Show all working steps. Use the formula sheet for reference.', status: 'Active' },
  { id: 'tpl-003', name: 'Science Lab Report', taskType: 'Activity', subjectName: 'Science', suggestedDurationMinutes: 50, recommendedForLevels: ['Grade 8', 'Grade 9', 'Grade 10'], instructionsTemplate: 'Record your observations from today\'s experiment. Include labeled diagrams and conclude with your findings.', status: 'Active' },
  { id: 'tpl-004', name: 'Creative Writing Prompt', taskType: 'Homework', subjectName: 'English', suggestedDurationMinutes: 40, recommendedForLevels: ['Grade 7', 'Grade 8'], instructionsTemplate: 'Write a {word_count}-word creative piece on the given prompt. Use descriptive language and at least {literary_devices} literary devices.', status: 'Active' },
  { id: 'tpl-005', name: 'Coding Challenge', taskType: 'Practice', subjectName: 'Computer Science', suggestedDurationMinutes: 90, recommendedForLevels: ['Grade 9', 'Grade 10'], instructionsTemplate: 'Write a program to solve the given problem. Include comments explaining your logic. Test your code with sample inputs.', status: 'Active' },
  { id: 'tpl-006', name: 'Map Work Exercise', taskType: 'Worksheet', subjectName: 'Social Studies', suggestedDurationMinutes: 30, recommendedForLevels: ['Grade 7', 'Grade 8'], instructionsTemplate: 'Mark all {locations} on the blank map provided. Use color coding as specified in the legend.', status: 'Active' },
  { id: 'tpl-007', name: 'Grammar Practice', taskType: 'Worksheet', subjectName: 'Hindi', suggestedDurationMinutes: 35, recommendedForLevels: ['Grade 7', 'Grade 8', 'Grade 9', 'Grade 10'], instructionsTemplate: 'Complete the grammar exercises on {topic}. Reference the textbook examples before attempting.', status: 'Active' },
  { id: 'tpl-008', name: 'Periodic Revision', taskType: 'Revision', subjectName: 'Multiple', suggestedDurationMinutes: 45, recommendedForLevels: ['Grade 8', 'Grade 9', 'Grade 10'], instructionsTemplate: 'Revise the following chapters for the upcoming test. Make notes on key concepts and practice numericals where applicable.', status: 'Draft' },
];
